origo-map/origo

- package.json
This PR updates package.json to OL 31.16.0. Only problem I have found are need for polyfills for animation och layerspy if using IE 9. At this point Origo doesn't depend on those functions.
> Upgraded to OL 3.16.0

- origo.js
- src/home.js
- src/viewer.js
Fixes #76 . A new control has been added for home. If extent is not provided as an option the extent will be calculated from the extent when the map is loaded. Is this ok @markus659 as a solution for #76?
> Added home control

- src/search.js
This PR fixes a bug in the search control when using geometryAttribute and title as options. The content was not showing in Popup.
> Fixed searchHandler bug

- src/search.js
This will fix #152. 
The PR removes bloodhound as a dependency for the search and replaces it with an ajax request. Changes has also been made so that search.js more closely follows the style guide. Most of the changes for the style guide was in the selectHandler function, but I don't think it should break anything, I would however appreciate an extra look on that function specifically.
> Removed bloodhound dependency

- index.json
- src/viewer.js
Fix to make proj4Defs not mandatory when using EPSG:3857 or 4326 that's
supported natively in Openlayers.
Solves #196
> Fix to make proj4Defs not mandatory

- src/layer/xyz.js
Edited the XYZ-source to support servers with different syntaxes for
TMS-services. Now you can specify the layer-part of the TMS request in
the config with the layerURL-parameter. 
Solves #251
> Extended TMS support

- src/editor.js
- src/editor/edithandler.js
A suggested fix for https://github.com/origo-map/origo/issues/6. With this change the user will be able to set an autoForm configuration for the editor control. With autoForm set to true (defaults to false), the attribute form will show up automatically after the feature has been drawn. 
Configuration example:
```json
{
"name": "editor",
"options": {
"editableLayers": ["test_byggnadsytor", "test_punkt"],
"isActive": true,
"autoSave": false,        
"autoForm": true
}
}
```
> Option to automatically show attribute form

- scss/_modal.scss
This is sort of related to #297. This PR raises the z-index of the modal screen (so that it is above the map menu, legend and control buttons.) The modal window itself will be on top of the modal screen.
> Adjusted modal z-index

- src/layer/wfs.js
Fixes #173 The loadingstrategy for WFS layers are configurable to load either the whole bbox or tiled. However, I excluded the all-option since it didn't work very well. The strategy can be set either on layer or source.
> Made wfs loadingstrategy configurable

- src/measure.js
Fixes #139 The measure tool is configurable. Default is both tools available and the line tool being the default. 
Configured this way:
{
"name": "measure",
"options": {
"area":false,
"default":"line"
}
},
> Made the measure tool configurable

- src/layer/vectortile.js
- src/maputils.js
- src/viewer.js
- tasks/build-ol-standard.json
Fixes #334 
Makes it possible to have a different tileGrid for vector tiles sources which is often necessary when combining with wms. Also changes the
alignTopLeft option to alignBottomLeft to match the default Openlayers behaviour.
> Custom tilegrid for vectortiles

- index.json
- src/mapmenu.js
- src/viewer.js
Fixes #346.
Option added to mapmenu control:
```
{
"name": "mapmenu",
"options": {
"isActive": false
}
}
```
Setting the ```isActive``` option to false is redundant and only for show - the variable is set to false by default.
> Added option to set mapmenu to open on load

- examples/editor.json
- package.json
I've tested ol 4.5.0 and I only stumbled on one problem. I got problems with reading ags tile. I hade to change the projection code name to 3010 for proj4defs, instead of EPSG:3010 to make it work. For those using Arc GIS server map services this is an important change.
> Updated to ol450

- src/featureinfo.js
- src/style.js
Fixes 417. A selection style can for example be added like this:
```JSON
"featureinfoOptions": {
"overlay": true,
"hitTolerance": 5,
"selectionStyles": {
"Point": [{
"circle": {
"radius": 5,
"stroke": {
"color": [0, 153, 255, 1],
"width": 0
},
"fill": {
"color": [0, 153, 255, 1]
}
}
}],
"LineString": [{
"stroke": {
"color": [255, 255, 255, 1],
"width": 5
}
},
{
"stroke": {
"color": [0, 153, 255, 1],
"width": 3
}
}
],
"Polygon": [{
"stroke": {
"color": [255, 255, 255, 1],
"width": 5
}
},
{
"stroke": {
"color": [0, 153, 255, 1],
"width": 3
}
}
]
}
}
```
> Added option to add selection style

- src/featureinfo.js
- src/getfeatureinfo.js
Fixes #449
Adds a titleAttribute option for layers to show a attribute value instead of the layer name as the title in the popup/sidebar.
> Show attribute as title

- .gitignore
- package.json
- tasks/webpack.copy-dev.js
Fixes #596 
Added new build script, adding build-dev folder.
Notes:
- Use build-dev script for development (or production) builds that should be ignored by git.
- Use original build script for release builds
> Ignore build folder

- src/controls/splash.js
This fixes #591. It is configured like so:
```json
{
"name": "splash",
"options": {
"url": "test.html",
"hideButton": {
"visible": true,
"hideText": "Visa inte fler gånger",
"confirmText": "Vill du verkligen inte se den här informationen igen?"
}
}
}
```
The only thing needed is the "visible" option, the text configurations are optional.
> Add button to hide splash

- package.json
- src/utils/legendmaker.js
if there is an icon in the style config of a layer that is flagged as extendedLegend like:
```
{
"icon": {
"src": "url request to GetLegendGraphic or any other statis asset"
},
"extendedLegend": true
}
```
then it will be embedded in the legend instead of the usual legend.
Related issue: #394
> Extended legend

- src/controls/legend/group.js
- src/ui/collapse.js
@mulfvik
Fixes #245, rewrote #503
By default you expand/collapse subgroups when ticking the subgroups checkbox. However you can override this by setting `"autoExpand": false` for a certain group.
> Autotoggle subgroups

- src/geometry/getcenter.js
- src/utils/replacer.js
Fixes #687.
Can be tested using the default config while adding the snippet below as an attribute to the 'origo-cities' layer.
```
{
"html": "<a href='https://www.google.se/maps/dir//{{@center(EPSG:4326,reverse)}}/@{{@center(EPSG:4326,reverse)}}' target='_blank' style='float: right'>Directions &raquo;</a>"
}
```
This PR is a quick fix to solve the issue mentioned above. But it only works if two arguments are passed to the @&#x200B;center helper function. E.g. 'EPSG:4326' and 'reverse' in the snippet above. If the 'reverse' argument is omitted, an empty argument must be passed to the function, like this (note the trailing comma separator):
```
@center(EPSG:4326,)
```
This is, in part, because of the way the searchAndReplace function is written, including a helper function call with …
> Fixed @center coordinate transformation bug

- src/controls/legend.js
Fixes #703
Adds a close button in the lower right, similar to the one in the map menu.
> Adds close button

- scss/_measure.scss
- scss/ui/_button.scss
Fixes #738 
Makes an exception for the measure icons (they are to big to fit inside the round icons) and reverts the ui button.css to previous state.
> Fix for background maps and measure icons

- src/layer/geojson.js
- src/layer/wfs.js
Fixes # 734
Adds projection option for wfs and geojson.
Simply set "projection":"EPSG:4326" to request features in another reference system and Origo will handle the transformation. The proj4Defs has to be configured in index.json unless it's EPSG:4326 or 3857.
> Adds projection option for wfs and geojson

- src/controls/search.js
Proposes to fix #425 , same as old PR #426, as agreed. (ESlint doesn't like a conditional return statement; I can't tell that this causes a functional issue however.) Movies:
Tested with V:ås external map's search back end, clicking hits does not pan and zoom by default neither with the current search nor the slightly altered version proposed here, perhaps a trivial thing, may be that someone else is interested in testing.
Edit. Yeah, two movies of unequal lenghts autoplaying right next to each other is a bit annoying
> Markus' search suggestions fix

- src/controls/geoposition.js
Fixes #752 
```
{
"name": "geoposition", 
"options": {
"active": true,
"panTo": false
}
}
```
> panTo option for geoposition control

- src/map.js
- src/viewer.js
Satisfies #759 
Currently as link in the issue states this property (still) defaults to false in OL6 but the behaviour around scroll wheels on mice appears to differ, as mentioned in the issue. The default property in this PR is false, the important bit to me is that the option joins the mothership.
> Enables the constrainResolution option for an Origo map

- scss/_scalepicker.scss
Fixes #780 
Partly fixes the issue by removing the width for scalepicker. However, fitting scalepicker and position in the left side of the footer can be an issue when working on a smaller browser window/screen. The footer may need an overhaul.
> Removed width in scalepicker

- scss/_modal.scss
- src/featureinfo.js
- src/getattributes.js
- src/ui/modal.js
Fixes #381 
Add target: modal or modal-full to open links in modal window instead of a new window. Used along with url. 
Example:
```
{
"name": "name",
"url": "url",
"target": "modal-full"
}
```
> Modal iframe

- src/controls/editor/edithandler.js
Fixes #546.
Adds a simple check if `geometryType` is set when the draw tool is activated. If not set, an alert message will tell the user that `geometryType` is missing.
Can be tested on empty, editable layers. Please note that if any features are present in the layer, `geometryType` will be set automatically, based on those feature types, and no message will be prompted.
The documentation will be updated with information regarding this.
> Added geometryType check and alert

- src/style.js
Fixes #457.
Allows icon rotation to be set based on an attribute by enclosing the attribute name in double curly braces, eg. `"rotation": "{{rotationAttributeName}}"`. The rotation value should be expressed in degrees. 
Config for testing can be found [here](https://gis.hudiksvall.se/examples/rotation.json).
> Added rotation by attribute for icons

- src/controls/legend.js
- src/controls/mapmenu.js
Fixes #179.
Adds the option `"autoHide"` to the mapmenu control. It has three different settings: `"always"`. `"mobile"` and `"never"` (default).
`"always"` always closes the mapmenu when clicking the map.
`"mobile"` hides the mapmenu when clicking the map if the map size is `m`, `s` or `xs` (see breakpoints in origo.js)
`"never"` never closes the mapmenu when clicking the map.
This function could easily be added to the legend as well.
> Hide mapmenu on mapclick

- src/getattributes.js
Fixes #660 
If url-value is not an attribute it checks if its a valid url
```
{
"title": "Some title",
"url": "//www.static.url/that/is?true=yes",
"target": "modal"
}
],
```
> Makes it possible to use static urls as attributes

- src/getattributes.js
Fixes #864.
Another condition was added for featureinfo popup list elements to be added to the DOM, requiring that the list item has contents (`.innerHTML.length > 0`).
> Require list items contents to add them to the feature info popup DOM

- src/layer/agsmap.js
Fixes #872.
Can be tested with the release test config found [here](https://www.malardalskartan.se/origo/v2.0.1/test.json). Just change the layer "isbanor" to this:
```
{
"name": "isbanor",
"id": "0",
"source": "ags_tile_vasteras",
"style": "isbanor",
"title": "AGS map service",
"group": "layers",
"type": "AGS_MAP",
"renderMode": "image",
"visible": false,
"queryable": true,
"attributes": [{
"name": "PLATS"
}, {
"html": "<a href='http://www.vasteras.se/uppleva-och-gora/idrott-och-friluftsliv/skridskoakning.html' target='_blank'>Läs mer &raquo;</a>"
}]
}
```
> Fixed broken function call in AGS_MAP

- src/controls/search.js
Fixes #868.
A `groupSuggestions` option is added for the Search control which replaces `layerNameAttribute` in controlling whether or not to group suggestions.
The titles for suggestion groups are now fetched the same way as the titles for feature info popups, providing more consistency and flexibility, such as the possibility to add suggestion group titles for single layer searches or searches without defined map layers.
> New `groupSuggestions` option, and group titles same as in feature info popups

- scss/origo.scss
- src/viewer.js
Fixes #883 
The assignment in viewer.js isn't as pretty anymore but it seems robust and now it cares about the visibility param of mapGrid under pageSettings, refers to the (previously disabled) o-map-grid and usage should rhyme with the documentation (defaults to false, visibility:true brings the graph paper).
> Makes the mapgrid available again

- src/featureinfo.js
An event is triggered when featureinfo is triggered. The event carries the currently displayed featureinfo item as a parameter.
Fixes #923.
> Added toggleFeatureinfo event

- src/controls/legend/overlays.js
- src/ui/collapse.js
- src/ui/slidenav.js
First suggestion, rough draft .. 
fixes #691 , kind of : ) 
This is how it currently is:
Compared to what this patch does:
> Introduces a positional memory property for the legend's scrollbar

- src/layer/agsfeature.js
- src/layer/wfs.js
- src/utils/replacer.js
Fixes #965. This is only available for layer types where filtering is already implemented, i.e. WFS and AGS_FEATURE.
Configure like this:
`"filter": "someAttribute={{someGlobalVariable}}"`
or
`"filter": "someAttribute={{sessionStorage.someVariable}}"`
> Added global variable filtering

- src/controls/legend.js
resolves #964 
Instead of creating a getter for the component, as described in the issue, I went with an add function instead.
The addButtonToTools()-function handles logic depending on how many buttons has been added. If there is only one button it will be to the right in Legend, but additional buttons will fill from the left. The tools component will be added regardless if any buttons will be added, but it will be hidden until a button is added.
As can be seen in the commit, the button in legend.js can also use the function.
No buttons:
One button:
Two buttons:
Four buttons:
How a plugin can add a button:
> Add buttons to legend tools, available for plugins

- src/controls/sharemap.js
- src/permalink/permalink.js
- src/permalink/permalinkstore.js
resolves #959 
Tested by having added layers (added with layermanager) in a map and then sharing the map to see if the added layers are still in the map. Sharemap used "storeMethod": "saveStateToServer".
The changes done in the Origo core can be seen in the commit, but the plugin needs to take advantage of them for it to work.
Example usage with specific code from Eskilstuna's layermanager:
Gets the sharemap controller and adds a key and a callback function.
Callback function assumes the state object as parameter.
Gets the mapstate params through viewer and uses them as needed.
> Possible for plugins to add params to mapstate

- src/controls/legend.js
fixes #974 
This PR remove the layermanager button from main origo. The button should be added in the plugin itself, which is possible with legend.js function: `addButtonToTools(button)`.
> Removes layermanager button in legend.js

- index.json
- scss/ui/_group-indication.scss
- scss/ui/_ui.scss
- src/controls/legend.js
- src/controls/legend/group.js
fixes #970 
Implementation of visual suggestion nr 3 with option to turn it off via index.json.
```
{
"name": "legend", 
"options": {
"labelOpacitySlider": "Opacity",
"useGroupIndication" : false
}
}
```
> Adds visual indication on groups with active layers

- src/permalink/permalinkparser.js
- src/permalink/permalinkstore.js
Proposes a fix for issue #978 
Appears to work for the mapState strategy too. Default increments for the opac slider are by 10% and the opac slider will pick the nearest 10% step. I am not certain of what dataTypes are available for the layerModel in permalinkparser.js, the suggested fix may have room for discussion : )
> Introduces 'o' for opacity url param in shared maps

- src/permalink/permalinkparser.js
Partially fixes #984  : a zoom of 9.763 in a shared link now produces that view, not zoom 9's.
> Makes a shared map's floating zoom respected.

- src/controls/mapmenu.js
Solves the problem of placing the menu below the legend.
> fixes #1013 brings the mapmenu to the top

- src/controls/legend.js
Fixes #1017. 
Reverted the legend `display` property back from `inline-block` to the original `flex` setting, thus _undoing_ part of the fix that solved #955. Curiously enough, it did not bring back the abstract flutter issue, at least not what I can see.
Please, when testing this, also try to reproduce the background maps abstract flutter issue, just to make sure I didn't manage to reintroduce that issue. Please note that the fluttering was mainly a Chrome issue.
> Fix for IE 11 legend scroll issue

- css/svg/material-icons.svg
- scss/ui/_icon.scss
- src/controls/geoposition.js
- src/ui/button.js
Fixes #1036.
Add the option `enableTracking: true` to, well, enable tracking. Just like this:
```
{
"name": "geoposition",
"options": {
"enableTracking": true
}
}
```
The geolocation control now has three modes - _Initial_, _Active_ and _Tracking_.
How to use it:
1. Press the Geolocation button once to enable geolocation (_Active Mode_)
2. Press the button again to activate tracking (note the subtle icon change) (_Tracking Mode_)
3. Press the button a third time to disable geolocation (_Initial Mode_)
Please note that if you drag the map while in _Tracking Mode_, the control will automatically switch back to _Active Mode_. This allows the user to pan around the map and then resume tracking by clicking the Geolocation button again.
> Added geoposition tracking mode

- src/featureinfo.js
- src/getattributes.js
Fixes #1082
This adds the option to set title in modal titlebar to static text, attribute value or URL of iframe.
This also adds a hint on the link that opens the modal.
New attribute option is added:
targetTitle (is used together with "target": "modal" or "target": "modal-full").
If targetTitle is not added the function would be the same as in current version, i.e URL of iframe is displayed.
Can be used with braces to show attribute value of geometry.
> Adds attribute option for title of modal displaying iframe.

- src/controls/editor/editform.js
- src/controls/editor/edithandler.js
- src/controls/editor/editortoolbar.js
- src/controls/editor/editsstore.js
Fixes #1090.
Instead of using `bubbles: true` to fix the non-responding editor button issue, another solution would be to dispatch the `enableInteraction` event directly on `document`. Not sure if that would cause other problems or not, though.
> Fixed editor bug after Jquery removal

- src/controls/legend.js
- src/ui/icon.js
Fixes #1093.
Correcting its title definition and generally letting SVG sprite Icons have their title elements set gives the "Turn Off Layers" button the same type of tooltip as the background buttons.
> Fix the title/tooltip in Legend control "Turn Off Layers" button

- src/controls/legend/overlay.js
Fixes #796 
Setting "exclusive": true for a group will only allow one layer to be visible at a time. Except when loading the map, that is.
> Adds the exclusive option for groups

- origo.js
- src/controls/splash.js
- src/viewer.js
Fixes #1092.
Adds a new option to the Splash control; `hideWhenEmbedded` which defaults to false.
If set to true, the modal is not displayed when the map is embedded.
```
{
"name": "splash",
"options": {
"title": "hideWhenEmbedded",
"url": "splash/splash-content.html",
"hideButton": {
"visible": true
},
"hideWhenEmbedded": true
}
},
```
> New option hideWhenEmbedded for all controls, by including control options in Viewer's addControl

- scss/ui/_collapse.scss
- scss/ui/_dropdown.scss
- src/controls/print/print-settings.js
- src/ui/dropdown.js
Fixes #1114.
Animation broke due to changes for the print control (#1037), which also affected the legend and any component using the `collapse-container` class.
> Fixed broken legend animation

- src/controls/measure.js
Fixes #1123 
Adds the possibility to not use hectares in area measuring. Default value is true, so if not specified it will use hectares.
```
{
"name": "measure",
"options": {
"useHectare": false
}
}
```
> Make it optionally to use hectare

- src/loadresources.js
Fixes #1109.
Loops through the controls from the config and adds them to the array of default controls, unless the control is already among the defaults. If a control in the config is also among the default controls, they are merged.
This is to produce the following behavior:
- If, in the future, a default controls is defined with default options, then those options should be included
- If a default control is also defined in the config, the options in the config should be combined with the default options
- If the default definition and the config define the same option, the value in the config will overwrite the default value.
> Merge (assign) config options for default controls

- src/controls/zoom.js
Further partially fixes #984 (see the last comment there).
If constrainResolution:true for a map and the plus or minus zoom buttons are clicked repeatedly in quick succession the viewer will end up at a scale not defined in the list of resolutions given for the map. If the scale control is employed this will result in 1:529 for example instead of the preset 1:500 and the WMS background map will be a bit blurry. The map view including the scale will correct themselves if the map is panned but a user won't always do that before zooming in and out further (which doesn't generally help).
The issue seems to be because of the animate() method for the zoom buttons and its duration of 250msecs. There's a check and a cancellation of running animations that triggers if you zoom in repeatedly faster …
> Proposed workaround for missed scales when constrainResolution:true

- scss/_tooltip.scss
Fixes #1166 
Shows the tooltip for 3 seconds on touch devices unless other interaction occurs. Changes also shows tooltips with shorter delay.
> Added an animation for non hover devices

- src/controls/editor/editform.js
- src/controls/editor/edithandler.js
Fixes #1183. It seems a few badly translated jquery crumbs got left behind.
Oh, you can use the config snippet below for testing. Just change `attributes` for the `editor_point` layer into this:
```
{
"name": "name",
"title": "Name: ",
"type": "text",
"maxLength": 50
},
{
"name": "type",
"title": "category: ",
"type": "dropdown",
"options": [ "category_1", "category_2", "category_3" ]
},
{
"name": "comments",
"title": "subcategory: ",
"type": "dropdown",
"constraint": "change:type:category_1",
"options": [ "subcategory_1", "subcategory_2", "subcategory_3" ]
}
]
```
> Removed jquery selected nonsense

- src/getattributes.js
Closes #1187 
Adds the possibility to split a attribute for a layer.
`{
"url": "url",
"splitter": ",",
"title": "Link"
}`
> Attribute splitter for url and img

- src/viewer.js
Fixes #1197 
The getLayers function in viewer will instead of returning a layerGroup return the individual layers in the group. I have not thoroughly tested how this affect other tools but I am not aware of any that uses the getLayers in that way.
> Make getLayers aware of layers in groups

- src/featureinfo.js
- src/viewer.js
Fixes #969  (well it's something to talk about and limited in scope, see below)
It targets wfs layers with the "__" naming scheme as shown in the origo layer documentation.
WFS layers because I have been unable to reproduce the issue with the default geojson layer, as mentioned in the related issue. WMS layers don't get to have selections with info popups in shared maps and other layers would need to be tested, but the suggested changes should only affect WFS layers because it seemed they primarily are treated special and are mentioned in the docs  (("__") I mean. Well, besides WMS layers but as mentioned they don't count)
It seems to work when I define the same wfs layer twice in a group layer, suffixing the names with "__rust" and "__11"
> Share wfs layer selection amelioration

- package-lock.json
This fixes vulnerabilities identified by npm when performing a clean `npm i`. The changes generated in the package-lock.json are from executing `npm audit fix`.
> Fix npm identified vulnerability in elliptic and bn modul

- src/controls/editor/copyTool.js
- src/controls/editor/drawtools.js
- src/controls/editor/editdispatcher.js
- src/controls/editor/edithandler.js
- src/extensions.js
Implementation for #1223. Possibility to copy a geometry from one layer to another.
Instead of polluting edithandler with if:s everywhere, as the copy tool does not work like openlayers draw interaction, I have introduced the concept of _custom draw tools_, external to open layers. What it basically means is that it is possible to send an event containing a new feature to edithandler and it will be added just as if a new feature had been created inside the edithandler. With this framework in place it is possible to add more tools without having to change edithandler.
The actual copying is performed in a new tool: copyTool, that is added to the drawTools menu using configuration. The implementation is rather rudimentary and can only select one feature from one of the configured source …
> Copy geometry

- src/layer.js
Fixes #1212.
Just add `cssFilter` or `blendingMode` properties to any layer in the config. Please use the documentation on [CSS filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) and [blending modes](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) for guidance.
Examples:
~~`"cssFilter": "brightness(50%) contrast(10%)"`~~
~~or~~
~~`"blendingMode": "difference"`~~
"css": {"filter": "brightness(1.2) contrast(2)", "mix-blend-mode": "multiply"}
EDIT
Oh, and please note that IE is not particularly fond of any of this...
> Added blending modes, CSS filter

- src/layer/geojson.js
Add the headers that is to be sent as a object in the layers config
`"headers": { "Accept": "application/geo+json" }`
> Adds the option to send headers when requesting url

- src/layer/geojson.js
Fixes #1232
Geojson features gets ID in this order:
1. The id property of the feature object (this is the correct geojson way of doing it)
2. The id property of the properties object (can be set to a different property on layer level, defaults to "idField": "id")
3. Incremented value starting at 1000000
This feature will get id 1:
{ "type": "Feature", "id": 1, "properties": { "id": 12, "name": "Karlstad" }, "geometry": { "type": "Point", "coordinates": [ 1503136, 8262205 ] } }
> Fixes geojson feature ids

- src/viewer.js
Fixes #1239 . (Negation is because of eslint(no-shadow))
Plugins can be added if isNotEmbedded is true or not depending on whether if one wishes them when the map is embedded or not
`
origo.on('load', function (viewer) {
if (viewer.isNotEmbedded()) {
var draw = Draw({..`
> Expose the embedded status of the viewer

- src/controls/editor/edithandler.js
Closes #878 
Makes it possible to specify multiple alternative that will show a field in editor popup
```
{
"name": "topptavla",
"title": "Stolpe, topptavla: ",
"type": "dropdown",
"maxLength": 30,
"options": [
"På stolpe",
"På väderskydd",
"Annan plats",
"Finns ej"
]
},
{
"name": "topptavla_skick",
"title": "Topptavla skick: ",
"type": "dropdown",
"maxLength": 30,
"constraint": "change:topptavla:[På stolpe,På väderskydd,Annan plats]",
"options": [
"Bra",
"Dålig "
]
},
```
> Multiple alternative will show a field

- src/controls/print/print-interaction-toggle.js
- src/map.js
- src/mapinteractions.js
Closes #1244
Usage for turning of embedded mapinteractions from config:
```
"pageSettings": {
"mapInteractions": {
"embedded": false
}
},
```
> Possibility to shut of special mapinteractions for embedded maps

- src/utils/download.js
Fixes #1282.
The print control uses the [printToScalePDF()](https://github.com/origo-map/origo/blob/d279d9c1f3d230c97a7af77e08b2bd7a2cb4c744/src/utils/download.js#L116) function in [utils/download.js](https://github.com/origo-map/origo/blob/master/src/utils/download.js) to generate downloadable PDFs.
This adds the elements `o-print-footer` and `o-print-footer-left` to the list of `o-print`-related elements that _should_ be included in the print (i e not excluded by the filter).
> Exclude print footer from filter (so it prints)

- src/utils/download.js
Fixes #1285.
The print filter checks the `className` property of each DOM element supplied using `indexOf()` which assumes that `className` is always a string. In the case of the close button of the featureinfo overlay, its `<svg>` and `<use>` elements have objects as their `className` property.
In these cases, classes set on those elements can instead be accessed through their `classList` property.
> Fix for SVG errors when printing to PDF with featureinfo overlay

- src/utils/legendmaker.js
Fixes #1290.
Pretty self-explanatory. If a style object has multiple style types combined, the text style should have the lowest priority when it comes to selecting icons for the legend.
> Use text for legend layer header as last resort

- src/controls/measure.js
Demo of label not added until more than one segment is added:
> Segment labels don't show on single segment

- src/style.js
More filtering on style as mentioned in #858
In thematic style add ' && ' to do AND filtering or ' || ' to do OR filtering.
Can be used multiple times, but not combine AND and OR filtering on the same filter
```
"filter": "[zon] == '5' && [status] == 'Avstängd'"
"filter": "[zon] == '5' || [status] == 'Avstängd'"
```
> Adds AND or OR filtering on style

- src/controls/legend/group.js
Fixes #502.
Adds the option `toggleAll` to (sub)groups. Default is `true`.
Setting `toggleAll` to false on a subgroup will remove the group toggle ability. Unlike the `exclusive` option, this will not restrict the ability to toggle individual layers on/off at will.
> Added option to disable the subgroup toggle-all function

- src/featureinfo.js
- src/oglide.js
[Fix for issue 1310](https://github.com/origo-map/origo/issues/1310)
Two problems:
1) The toggle feature event was not triggered when the first feature is loaded
2) It was triggered too early and excessively. For example on carousell click irrespective of whether the click triggers the next feature in the carrousell or not.
This is most noteable when using the voting section of the dialogue-plugin.
These problems are solved by 
1) Always triggering the toggleFeatureinfo event when the first or a single feature is loaded.
2) Changing the glidejs event from 'move' to 'run.after', which is triggered only after a new feature is loaded in the carousell.
[glidejs events](https://glidejs.com/docs/events/)
> fix: incorrect triggering toggleFeatureinfo event

- src/selectionmanager.js
Fixes #1275 and partially #1256.
Can be used like this to listen to changes in selection for a certain layer and deal with that, eg update an external table:
```
viewer.getSelectionManager().createSelectionGroup('layername', 'layertitle');
viewer.getSelectionManager().getUrval().get('layername').getSourceLayer().on('change', function(){runSomeFunction(this)});
```
> Get selection from api

- src/controls/print/index.js
Relates to #1158.
Adds a new config option for the print control:
`"placement": ["menu", "screen"]`
The new option controls whether to put buttons for opening the print control on the map screen, in the menu or both.
Default is  `"placement": ["menu"]`.
> Configurable print button placement

- src/featureinfo.js
- src/getfeatureinfo.js
- src/selectionmanager.js
Resolves #1256.  Adds an event `changeselection` on the FeatureInfo component. The event is emitted when a new selection is made in FeatureInfo regardless of which infowindow is used. For overlay and sidebar the event will be triggered on opening the dialog and when the carousel changes visible item. For infowindow the event is emitted when a new row is highlighted. The event data contain a SelectedItem with the selected item.  The `toggleFeatureinfo` custom event dispatched on the global _document_ object is also dispatched in the exact same way containing the same data, but is not considered a part of the API and should not be used outside origo.
Intended usage: 
```
var origo = Origo('index.json');
origo.api().getFeatureinfo().on('changeselection', evt => doWhatever(evt))
```
Also adds …
> FeatureInfo API

- src/controls/bookmarks.js
Fixes #1300.
Adds a new config option to the bookmarks control: `autoClose`. When set to `true` and using screen size `m`, `s` or `xs`, the popup will close after clicking on a bookmarks link. Default is `false`.
```
{
"name": "bookmarks",
"options": {
"title": "Bookmarks",
"isActive": true,
"duration": 1000,
"autoClose": true,
"items": [
{
"name": "Hudiksvall",
"coordinates": [1904063, 8794995]
},
{
"name": "Karlstad",
"coordinates": [1503136, 8262205]
},
{
"name": "Sigtuna",
"coordinates": [1986473, 8315061],
"zoomLevel": 10
}
]
}
}
```
> New config option to close the bookmarks popup when clicking on a link on small screens

- src/controls/editor/editform.js
- src/controls/editor/edithandler.js
Solves #1316. Makes it possible to batch edit attributes using the normal attribute editor form.
To batch edit attributes, the attribute must be configured with `"allowBatchEdit": true` in the _attributes_ section of the layer configuration.
If more than one feature is selected when the attribute edit form is opened, there will be a checkbox for each attribute that can be changed. Upon completion, all selected features will receive the new value for the attributes that have been checked.
To select multiple features use shift-click in the map.
> Batch edit attributes

- origo.js
- src/viewer.js
Fixes #1345 
Dispatches an event in viewer.js when layers and controls have been added.
> Origo load event

- src/controls/print/index.js
- src/controls/print/print-component.js
- src/controls/print/set-scale-control.js
- src/layer/wms.js
Fix for #1167. Recalculates the resolutions array when entering print preview and restores them when print component is closed. By doing this the scale selector and the print preview gets the same scale when _constrainResolution_ is set regardless of DPI setting. 
It also recalculates max zoom and min zoom to allow the print preview to zoom beyond the original limits to provide for other DPI settings. As an implementation note, temporarily setting _constrainResolution_ on the map is not sufficient to solve the min and max zoom problem, as that parameter only controls if zoom values between the defined levels are allowed.
The feature is opt-out as it is most likely how it should work, but if it just happens to destroy something else, it can be turned off by setting …
> Recalculate resolutions when entering print view

- src/loadresources.js
- src/utils/stripjsoncomments.js
Closes #1380 
Support for c-style one line comments: `// This is a comment` and multi line comments: `/* This is also a comment */`. It does NOT support nested multiline comments and does not fix any syntactical errors that may occur due to parts being commented out. All characters, except new lines, in comments are replaced with spaces in order to keep same size and line numbering.
Also added better json parsing error message which throws an error containing the row number and an excerpt of the configuration at the location of the error instead of just file position.
> Comments in configuration

- src/featureinfo.js
Fixes #1363 
The  `changeselection` event is only emitted when the
item actually is a SelectedItem.
> Only emit event for SelectedItem

- src/controls/editor/attachmentsform.js
- src/controls/editor/edithandler.js
- src/featureinfo.js
- src/getattributes.js
- src/getfeatureinfo.js
- src/layer.js
- src/utils/attachmentclient.js
- src/utils/groupby.js
Closes #1314 
Intoduces the concept of attachments. Attachments are files that are not a part of a feature, but are related to a feature.  The implementation only includes the client side part of the attachment handling. In order to actually use attachments an attachment server is needed. The attachment handling is pretty much like in ArcGis and the server interface is actually taken from ArcGis server specification.
This PR consists of several parts:
1. Code that comprises an attachment server client repository class.
2. Code to include insertion and deletions in the attributes editor
3. Code to create temporary attributes from the attachments links
4. A new attribute formatter "linktext"
5. As a bonus, a utility function groupBy is added.
**Configuration**
Configuration is performed by …
> #1314 Attachments

- scss/_bookmark.scss
- scss/_ol.scss
- scss/_position.scss
- scss/_viewer.scss
- scss/ui/_button.scss
- scss/ui/_dropdown.scss
- scss/ui/_input.scss
Fixes #1394 
Changed to focus-visible from focus to only display clear focus when using keyboard navigation and not on mouse clicks. 
One problem is that focus-visible is a new feature in web browser and only got adopted as of 2021. Thoose with old browser will not see clearly focused buttons when tabbing.
> Changed to focus-visible

- src/loadresources.js
Fixes #1400 in a very simple way. For example, it makes it possible to add multiple About or Link controls with different settings in the config. It also makes it possible to add multiple instances of _any_ control that is not implemented as a default control in origo.js, which might be considered as a negative side effect.
A different approach could be to modify the Link and About controls (and possibly others) to accept multiple links/abouts. However, making such an implementation backwards compatible would probably be a bit messy since old style single links would have to be handled one way, and new style multiple links a different way.
> Allow multiple instances of a control

- src/getattributes.js
Closes #1414 
```
{
"name":"length",
"title": "Length: ",
"prefix": "about ",
"suffix": " km"
}
]
```
> Adds option to add prefix/suffix to attribute value

- src/controls/editor/attachmentsform.js
- src/controls/search.js
- src/featureinfo.js
- src/viewer.js
Fixes #1405 by disabling the pan to overlay before search zooms to the search result feature, as the pan will be overrun anyway.
Added an option to disable panning when displaying popup as the panning animation was created using relative coordinates which became incorrect when immediately zooming to another extent. Also changed all known places where render() is called to support or make use of the option too keep old behavior.
> Fix for search incorrect zoom

- src/controls/search.js
Fixes #1141.
Piggybacks on the listener on the `focus` event to show any suggestions stored from a completed search.
> Open current suggestions on focus in Search control

- src/ui/modal.js
Closes #1406 
Added possibility to specify the contents of a Modal as a `HTMLElement` object in order to pre build the contents complete with eventhandlers and all.
This PR adds a `contentElement` parameter to Modal constructor options. The `contentElement`  should be a  `HTMLElement` containing the content. If present, it takes precedence over the `content` option.
Hard to test, as it is only an api change and not used anywhere, but can be tested by calling `Origo.ui.Modal()` from console and also by regression tests of existing modals.
As a note this feature could probably have been implemented by allowing either text or HTMLElement in the content option, but in order to keep absolute backwards compability it is implemented as a new option. There is a small risk that the implementation …
> HTMLElement as modal content

- src/controls/search.js
Fixes #1418.
Checks if the `url` already has a parameter question mark (and possibly additional parameters) before adding a new one.
Now, URLs such as `http://localhost:3001/origoserver/search?limit=10` will work.
Also adds a new config option for the Search control: `queryParameterName` that defaults to `q` and can be used to change the name of the query parameter if connecting to some other external service.
> Allows additional URL parameters in the Search control and a custom search string parameter name

- src/getattributes.js
Format the datetime value if it is a valid datetime otherwise leave as is.
Example of how the datetime can be formatted:
```
{
"name":"dateLastPreparation",
"title": "Senast preparerad: ",
"formatDatetime": {"locale": "sv-SE", "options": { "dateStyle": "full", "timeStyle": "long" }}
}
```
```
{
"name":"dateLastPreparation",
"title": "Senast preparerad: ",
"formatDatetime": {"locale": "en-US", "options": { "weekday": "long", "year": "numeric", "month": "long", "day": "numeric" }}
}
```
More formatting options can be found here: 
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)
Test config: …
> Format the datetime value

- src/controls/print/print-component.js
Fixes #1422
__Beware__: this is a monkey patch that overrides an internal OL function and may very well break when OL is updated.
In order to minimise side effects, the monkey patch is only active when print preview is active.
Not all events are fixed with this PR as they internally in OL uses another way of calculating the position of the event. Pinch zoom and pan are among those interaction that is not fixed.
> Monkey patch OL to correct position of mouse events in print preview

- src/maputils.js
Fixes #1449 
Used like this:
_transformCoordinate(coordinate, source, destination)_
origo.api().getMapUtils().transformCoordinate([13.5,59.38],'EPSG:4326','EPSG:3857')
Can be used to set center in another coordinate system:
origo.api().getMap().getView().setCenter(origo.api().getMapUtils().transformCoordinate([13.5,59.38],'EPSG:4326','EPSG:3857'));
(Coordinate systems must be defined in the config unless using EPSG:3857 or EPSG:4326)
> Added transformCoordinate to maputils

- src/infowindow.js
- src/utils.js
- src/utils/exporttofile.js
Closes #1429
Adds an _export to file_ button to _infoWindow_.
Also exposes a utility function in the `Origo.Utils` "namespace" to export arbitrary features. Usage is documented in code.
Config by adding something like this to the `infoWindowoptions.export` configuration. It has the lowest precedence of the three kinds of export.
```
"clientExport": {
"buttonText" : "Exportera fil",
"layers": [ "SketchMultiPoint", "To2018_Swe99TMWhatever" ],
"format": "geojson"
}
```
`format` is the file extension of the file format to export. Currently supported is `'geojson'`, `'gpx'` and `'kml'` . In theory more formats are supported by openlayers, but I picked the subset that can be drag and dropped and has the writeFeatures function implemented.
`layers` specifies the SelectionGroup name for those …
> Export selection to local file

- src/controls/print/print-component.js
- src/viewer.js
Fixes #1446 
Uses the value from the id-option (if present) on wfs layers to construct the featureId when opening a shared map. The id option takes precedence over layer name as that's how the layer is created,
> Fix to support id parameter on wfs layers in sharemap

- src/layer/wfssource.js
Fixes #1470.
When constructing the WFS source URL, any parameters included will be kept and further parameters from Origo will be appended after an ampersand (&).
If a custom parameter would be in conflict with a parameter added by Origo, Origos parameter should override the custom parameter on account of being added last.
> Allow custom URL parameters in WFS sources

- src/controls/print/print-legend.js
Aims to fix #1488 
If a layer style definition has the extendedLegend-property (meaning true) the affected function will land at
```javascript
} else {
content = await getJSONContent(title);
```
which will for a Geoserver 2.16+ return rules for a pretty theme legend and for others, like an ArcGIS Server with WMS layers, return the title of the layer with no icon, even when printing an Image. #1484
> fix: fix geoserver wms theme layer print legend

- src/getfeatureinfo.js
Closes #1497 
```
"source": {
"local": {
"url": "http://localhost/geoserver/wms"
},
"lstY-strandskydd": {
"url": "https://ext-geodata-lokala.lansstyrelsen.se/arcgis/services/LSTY/lsty_wms_strandskydd/MapServer/WMSServer"
}
},
"layers": [
{   "name": "0",
"title": "LST Strandskyddsdispenser",
"queryable": true,
"visible": false,
"type": "WMS",
"group": "root",
"source": "lstY-strandskydd",
"style": "Strandskyddsdispenser",
"infoFormat": "application/geo+json"
},
```
> Fetch feature info in application/geo+json format

- src/controls/editor/editortoolbar.js
Hides layer selector button when only one layer is editable.
Hides save button when autosave option is true.
Closes #1494
> Auto hide layers and save button in editor

- src/controls/editor/editform.js
- src/controls/editor/edithandler.js
Closes #1495. 
Adds possibility to update feature variables from localStorage, sessionStorage or setting a timestamp. Configuration basically as in issue #1495, but `alwaysUpdate` is renamed to `updateOnEdit`  and added `useUTC` for timestamps to select between local time and UTC.
If type is timestamp it is possible to set a format depending on what the timestamp is for.
Time formats supported:
- `time` : hh:mm:ss. Used when database field is _time_ or _text_
- `date`: YYYY-MM-dd. Used when database field is _date_ or _text_
- `datetime`: "YYYY-MM-dd hh:mm:ss" Used when database field is text and you want a readable string.
- `timestamp`: Default. Can be parsed by most iso date time parsers. Used when database field is DateTime (or similar) or when using a _date_, _time_ or _datetime_ …
> Default values in editor

- src/controls/editor/editform.js
- src/controls/editor/edithandler.js
> Adds a abort button to editor form if autosave and autoform is true

- src/utils/download.js
Fixes #1484 so that Save image in print works for WMS layers with a style that references an URL elsewhere (subject to CORS); instead of a crash in the console (mine looks like
> Uncaught (in promise) DOMException: The operation is insecure.
)
styles not subject to CORS are (of course) not affected
If a remote style resides on a server not configured or not properly configured for CORS the Save image should now not crash but rather leave an empty space where the icon would be in the saved image legend
credits to @johnnyblasta who came up with the fix
> fix: allow styles subject to CORS to work with print - save image

- origo.js
- src/viewer.js
Resolves #1453.
This PR makes it possible to update the hash part of the url to change to another sharemap state.
The map is completely "rebooted" to fully reflect the new incoming map state. In order to do so without messing around too much in the viewer a completely new Viewer is created instead of trying to restore all state. As a new viewer is created, external code that uses the `'load'`-event should also reinitialise itself using the new viewer.
> Support for changing share map hash

- src/controls/print/print-resize.js
This PR contains fixes #1476 and fixes #1482.
It properly "resets" scaling by using the existing `setLayerScale` function using the "original" DPI value (currently hardcoded to 150 as in other parts of the code).
Selection style is corrected by setting the layer style rather than the style of individual features (fix written by @sweco-sefaed).
> Fix for #1476 and #1482 (correct styling upon exiting print view)

- DEVELOPING.md
- package.json
- src/controls/editor/editorlayers.js
- src/controls/editor/editortoolbar.js
- src/controls/legend/group.js
- src/controls/legend/overlays.js
- src/controls/print/print-settings.js
- src/controls/print/set-scale-control.js
- src/getattributes.js
- src/utils/isurl.js
- src/viewer.js
Fixes #1451 by obeying som rules. Also fixed that all files are linted independent of which npm script is run. (Sort of, `npm run lint` will lint all files in the src tree except those ignored in _.eslintignore_, the other scripts will lint what is actually bundled honoring _.eslintignore_ )
I also added some stuff to the documentation on how to lint.
> Fix lint errors

- src/controls/editor/editform.js
- src/controls/editor/edithandler.js
Closes #1519 and fixes #1520.
Adds the possibility to add which values a checkbox should use for checked and unchecked. As a bonus the checkbox is moved to the left of the label.
checkedValue defaults to 1 (backwards compatible)
uncheckedValue defaults to 0 (backwards compatible)
It is possible to only specify one of checkedValue and uncheckedValue and make it work, but I wouldn't recommend it as for backwards compatibility the logic interprets any truthy value as checked unless uncheckedValue is specified, but on save a specific value is set.
```json
{
"name": "fritext",
"title": "Check me out",
"type": "checkbox",
"config": {
"uncheckedValue": "okryzz",
"checkedValue": "kryzza lugnt"
}
}
```
> Editor checkbox value

- scss/origo.scss
- scss/ui/helpers/_animations.scss
- src/controls/print/print-component.js
- src/controls/print/print-toolbar.js
- src/loading.js
- src/ui/component.js
- src/viewer.js
* Show a loading spinner while exporting to PDF (fixes #1359)
* Disable print export buttons while the map is updating (prevents accidental incomplete exports due to pending tiles)
* Refactor the base `Component` to make use of ES6 class syntax as well as introduce a convenience `html` tagged template literal for use in `render()` methods
The third point is introduced in a way so that it does not affect its interface. If wanted it can be extracted into a separate PR.
> Print export progress, button disabling and slight Component refactor

- src/featureinfo.js
- src/getfeatureinfo.js
Fixes #1554
Layergroups needed to be split up and each layer in the group be handled as individual layers. This will make the title of the popup use the layer title rather than the layergroup title.
> Handle layergroups

- src/controls/legend/overlay.js
Fixes #1559 
Should be used with caution and works only for vector layers. It exports the features that has been requested from the server, thus works best with geojson-layers or wfs with strategy:all but is primarily intended for draw layers.
Configured like this:
>  {
"name": "origo-cities",
"title": "Origokommuner",
"group": "root",
"source": "data/origo-cities-3857.geojson",
"style": "origo-logo",
"type": "GEOJSON",
{
"name": "name"
}
],
"visible": true,
"exportable": true,
"exportFormat": "geojson" // ["geojson", "kml"]
}
exportFormat can be a string (geojson, gpx or kml) or an array of formats. Defaults to geojson in case om omitted or invalid.
> Adds export option for layers

- scss/_modal.scss
Fixes #1563, quick and dirty.
Can't see that `transform-style: preserve-3d` has been used for anything in particular in the past and I haven't noticed any negative side effect after removing it. But please, throw your weirdest modal configs at it and see if it breaks!
> Fix blurry editor form

- src/controls/print/print-component.js
- src/controls/print/print-toolbar.js
- src/loading.js
- src/ui/component.js
This PR reverts the component refactor from #1529, fixing group and subgroup expansion.
~The refactor of the base component in #1529 slightly changed how events where attached, which made it possible for onRender to be called more than once which in turn attached event handlers more than once, resulting in bugs like in #1551.~
~This PR fixes that by somewhat formalizing (and reducing) the handling of especially the "render" event. There is also commented out code to get a warning on similar issues (currently present in the print component, though without any user visible issues that I could find).~
Closes: #1551
> Fix group and subgroup expansion

- scss/ui/_flex.scss
- src/controls/legend/overlay.js
- src/ui/collapse.js
Closes #1528 
Extended legends (e.g composite WMS-layers and thematic vector layers) are displayed below the layer name in legend. Default they are collapsed and are displayed by clicking the extended/no symbol icon.
Layers that do not have an extended legend are affected in that way that clicking the symbol now does exactly nothing instead of toggling visibility.
Layers that does not have any symbol at all will display a _legend missing_ text when the list symbol is clicked, which is the same as in layer info.
To start with the extended legend visible add `'expanded ': true` to the layer configuration.
It supports changing symbology using the stylePicker.
__Known issues__
If a thematic symbology has a `'header': true` setting, the thematic symbology will not be available inline. The main …
> Extended legend inline

- src/layer/geojson.js
- src/layer/topojson.js
- src/layer/wfs.js
- src/layer/wfssource.js
Fixes #1523.
Had to copy and reset `extent` parameter to ensure backwards compatibility and to make sure it doesn't affect layer rendering since `extent` is also a native vector layer parameter.
> Make vector sources aware of custom layer extent

- scss/ui/_flex.scss
- scss/ui/_popup-menu.scss
- src/controls/legend.js
- src/controls/legend/overlay.js
- src/controls/legend/overlays.js
- src/controls/legend/visibleOverlays.js
- src/ui/collapse.js
- src/ui/popupmenu.js
- src/ui/slidenav.js
Fixes #1558 
Cleaned up a bit, hopefully didn't mess up anything
> Fix for popup menu

- src/layer/wms.js
Proposes to fix #1560 . Introduces two properties of a WMS layer:
```json
"hasThemeLegend": true,
"legendParams" : {
"scale" : 5000,
"legend_options" : "dpi:300"
}
```
Where `hasThemeLegend` is necessary for "auto" style creation for WMS layers with a theme legend (to extendedLegend) and
`legendParams` is more or less what @steff-o suggested in the related issue. 
Both properties are ignored if a `style` property also exists for the given WMS layer.
The default "scale" for the getLegendGraphic call (there needs to be a scale for scale dependant styles) is the largest scale of the configured map (because typically theme layers have more visible classes at a larger scale than at a smaller scale if scale dependant) however that value is overriden if `scale` is given as a `legendParam`.
The …
> feat: enable automatic style creation for wms layers' getLegendGraphic

- src/controls/print/print-legend.js
> fix: make sure all AGS layer ids compared in print-legend are numbers

- src/controls/splash.js
Fixes #1591 
Changes the key for splash control to consider the path of the map as well as map config.
Example key: `splashContent;/index.html;index` instead of just `splashContent`
This will make previous settings for splash visibility invalid so the splash will prompt no matter if the user has previously turned it off.
> fix: splash control with multiple maps

- src/controls/legend.js
Fixes #1599 
Adds a check whether a layer is in an exclusive group or not when activating layers in the layer search result list.
> fix: exclusive layers in legend search

- scss/_position.scss
- src/controls/position.js
Closes #1602. This PR contains code to format coordinates in the position control  in DMS-format and also enter coordinates in DMS-format in the go to coordinate function.
As the existing configuration made it impossible to add the same coordinate system twice, I added a new configuration format. The old one is still valid for backwards compatibility, but lacks the new functionality.
In the new configuration format it is possible to specify dms as format and also an optional precision parameter that controls how many decimals a coordinate should have.
Example configuration:
```json
{
"name": "position",
"options": {
"title": "Web Mercator",
"projections": [
{
"projectionCode": "EPSG:4326",
"projectionLabel": "Wgs84"
},
{
"projectionCode": "EPSG:4326",
"projectionLabel": "Wgs84 DMS", …
```
> feature: support for DMS in position control

- src/controls/legend/overlayproperties.js
- src/controls/print/print-legend.js
- src/layer/wms.js
Proposes to fix #1583 
Allows users to declare alternate styles for WMS-layers in the stylepicker. It is possible to declare whether a style is has theme. A title for the default style is declared by setting the `default` flag. Chosen style will be saved when sharing the map. 
Example of how to format the settings in json:
Will also take style-url for WMS-layers declared in json document into consideration before the url from layer source in the print legend.
> feature: enable WMS-layers in stylepicker

- src/controls/legend.js
Aims to fix #1585 
It could be seen as potentially incomplete (setting setVisibleLayersViewActive(true) again as opposed to toggling as suggested in the issue. I've not encountered any ill effects in preliminary testing however. With this our Layermanager-csw can as part of its onAdd() do:
```javascript
if(sharedLayers) {
ReadAddedLayersFromMapState(sharedLayers, viewer);
if (viewer.getControlByName('legend').getState().visibleLayersViewActive) {
viewer.getControlByName('legend').resetVisibleLayersView();
}
}
```
> fix: add method for plugins to regenerate visible layers

- src/controls/editor.js
- src/controls/editor/drawtools.js
- src/controls/editor/edithandler.js
- src/controls/editor/editorlayers.js
- src/controls/editor/editortoolbar.js
- src/dropdown.js
Closes #1615 and closes #1616. (Sorry had to implement them together)
Adds api functions to the Edit-component in order to make it possible to implement plug-in controls that can access the editor without having to make the user interact with the map or the editor toolbar.
All functions can be called without the editor actually being active (toolbar visible) and are accessed by getting a reference to the Edit-control: `viewer.getControlByName('editor');` and executing the methods on the component. All functions honor autoSave-setting.
_changeActiveLayer:(layerName)_ : Changes the editor's active layer. The layer must be a layer that is not configured as a table, i.e. it should have a geometry and configured as editable as usual. The selected layer is indicated in the toolbar.
_async …
> feature: editor api

- src/controls/print/print-resize.js
Fixes #1605 
Solves issue that arises when style is set on individual features for example in measure control, drag and drop control and LMSearch plugin.
> fix: reset features style after print control

- src/viewer.js
Aims to fix #1634 
A rather simple potential fix. Have tested:
- Sharing mapstate and hash
- Printing
- Combined with Show only visible layers
- WFS and WMS alt stylers
> fix: make layers with workspace:layer names work with stylePicker

- src/controls/print/print-component.js
Fixes #1665 
Lowered the pixelratio when printing if on iOS device. Also added touch.action: none for the print container since pinch zooming in the print preview also could make the print function crash.
> fix: crash when printing on iOS

- scss/_print.scss
- src/controls/print/print-component.js
- src/controls/print/print-toolbar.js
Aims to fix #1661 
(and prevent unnecessary event listening when the print panel isn't active)
> fix: really disable print buttons while print preview map is loading

- src/controls/legend/overlayproperties.js
- src/layer/wms.js
Aims to fix #1657 ie it adds the `legendParams` object property to the stylePicker for WMS-layers, so that alternative styles for a WMS layer can have such options for their legendGraphic as well as WMS-layers without a stylePicker and the default style of a WMS layer with a stylePicker.
Have run some basic tests on changing the style to a stylePicker style with legendParams, sharing, printing.
> Wms stylepicker legendparams

- src/controls/print/index.js
Aims to fix #1654 . Enables for instance `viewer.getControlByName('print').getPrintComponent().on('render', () => {` for something to happen when the print preview panel is opened. More things become possible.
> feature: make the central print component available externally

- src/controls/legend/overlay.js
- src/controls/legend/overlays.js
Fixes #1674
Setting "confirmRemoval": true pops up a confirm dialog window This commit also includes also removes redundant calls to removeOverlay-method and relies on the event instead.
> feature: confirm removal of layer

- origo.js
- package-lock.json
- package.json
- scss/ui/_collapse.scss
- src/controls/draganddrop.js
- src/controls/legend/group.js
Fixes #1692 
Set `draggable: true` to make a group sortable by dragging layers. Useful for groups with user added layers.
> feature: add draggable option for groups

- scss/ui/helpers/_text.scss
- src/controls/legend/overlay.js
> Break word

- src/featureinfo.js
- src/featureinfotemplates.js
- src/getattributes.js
- src/map.js
Fixes #1681 and #1690
Configured like:
```
"attributeAlias": {
"name":"Namn"
}
```
in the config. Can be tested by removing the attribute setting for the origo cities layer in the standard map.
> feature: featureinfo templates with alias and API functionality

- src/loadresources.js
Fixes #1716 
Makes it possible to add a mapState when initializing a map. A way to alter the default config eg when customizing a map based on the user
> feature: mapState as map parameter

- src/ui/collapse.js
> fix: only activate buttons on first level when expanding

- src/layer/wfs.js
- src/layer/wfssource.js
- src/layer/wms.js
Fixes #1754 
Set requestMethod: 'post' for either layer or source to make POST requests instead of GET
> feature: post method for wms and wfs

- src/controls/draganddrop.js
- src/controls/legend/overlay.js
Seeks to resolve #1758 . Drag-and-drop receives the `promptlessRemoval` option and makes it true by default, so it's opt-out.
Layers can have this property and then not cause a prompt to verify when being removed.
> feature: make prompt configurable for removable layers

- src/controls/draganddrop.js
- src/viewer.js
Fixes #1764, alternative solution to https://github.com/origo-map/origo/pull/1765
> fix: styling of draganddrop layers

- src/controls/draw.js
Aims to resolve #1778 . 
Edit: This changes draw so that it is always added and still shown in the menu, if placed in the menu. If placed on screen it is hidden. (Currently draw isn't added if `hideWhenEmbedded`)
> feature: add hide function for draw

- src/components/infowindow.js
- src/controls/editor.js
- src/controls/editor/edithandler.js
- src/ui/button.js
Fixes #612 List the features to be able to select overlapping features.
Can be turned off by setting `"featureList": false` in the editor options
Attributes to be showed in the infowindow is setup like this on layer level. Empty attributes won't be showed and the default is to just show the feature ID:
`"featureListAttributes": ["id", "name", "type"]`
> feature: pick feature in editor

- src/getattributes.js
Fixes #1774 
Test config:
```
{
"img": "bild",
"name": "bild",
"title": "Bild: ",
"type": "image"
}
```
> fix: let img attribute have precedence before name

- scss/_popup.scss
- src/featureinfo.js
Fixes #1760
When setting origostyle.overlayOptions.offset for a feature it will offset the popup overlay.
Use with caution because when having multiple features in the carousel it will only check the property of the first feature.
Eg:
Can be used like this:
```
const viewer = origo.api();
const layerOptions = {
group: 'root',
name: 'markerLayer',
title: 'Markers',
zIndex: 6,
styleByAttribute: true,
queryable: true,
removable: true,
visible: true,
source: 'none',
type: 'FEATURE',
attributes: [
{
html: '{{content}}'
}
],
style: viewer.getStylewindow().getStyleFunction
};
const layer = viewer.addLayer(layerOptions);
const coords = [1575114, 8396023];
const newFeature = viewer.getMapUtils().createPointFeature(coords, null);
newFeature.set('origostyle', {pointType: 'marker', overlayOptions: { …
```
> feature: add overlayOptions from the origostyle-object

- src/controls/legend/overlayproperties.js
Fixes #1788 
Used like this:
```
origo.api().getControlByName('legend').on('renderOverlayProperties', function(obj){
console.log(obj)
})
```
The event object is the overlayProperties component and the layer
> feature: overlayproperties event

- src/controls/editor/editform.js
- src/controls/editor/edithandler.js
Fixes #1757
Problem was that there was an asynchronous resize when the form is saved which messed up the current layer state variable.
Resolved by moving the resize to when the file is loaded (which in my opinion is more logical anyway). Previous implementation resized the image on save, which meant that the preview image was full resolution and the image was read twice.
The result should be the same which includes that the image is always resized to a max size of 600 pixels in the largest dimension. That can be overridden by setting a new max size by the undocumented maxSize option.
```JSON
{
"name": "name",
"type": "text"
},
{
"name": "imgsrc",
"type": "image",
"maxSize":  50
}
]
```
> Fix: Image in related table

- src/controls/draganddrop.js
Fixes #1792 
New options:
```
"zoomToExtent": true, // Adds zoom to layer option for the layer, default true
"zoomToExtentOnLoad": true // Zooms to layer extent  when loaded, default true
```
> feature: new options for draganddrop

- src/style.js
Fixes #1797.
Use like this:
```
"line": [
[
{
"stroke": {
"color": "rgba(103,60,31,1.0)",
"width": 1
}
},
{
"icon": {
"size": [
23,
36
],
"src": "img/png/droppe.png"
},
"geometry": "startPoint"
}
]
]
```
> feature: start point style geometry option

- src/layer/wms.js
Aims to fix #1805 . (Seems to createObjectUrls before revokingObjectUrls)
> fix: make imageLoadFunction revokeObjectURL

- src/controls/print/index.js
- src/controls/print/print-component.js
- src/controls/print/print-settings.js
Fixes #1807 
Adding ``settingsExpanded": true`` print option will make the settings window appear when opening the print preview page.
> feature: added settingsExpanded option for print control

- src/ui/modal.js
- src/utils.js
Closes #1729
Makes all instances of `modal` draggable. No configuration necessary or even possible. Just click-drag the header of any modal and watch the magic happen.
There will be a race for merge conflict in _utils.js_ with #1751, but I stole the code from there so the conflict will be easy to merge unless @jokd changes more stuff.
> feature: Made modal draggable

- src/maputils.js
Fixes #1834
If origin is set as a `tileGridOptions` it is used instead of top/bottom left coordinate
> feature: origin as tileGridOptions

- src/controls/print/print-settings.template.js
> fix: Rename print legend to teckenförklaring

- src/controls/draw/drawhandler.js
Fixes #1862 
To NOT use this feature:
`"zoomToExtent": false`
Defaults to true
> feature: add zoomToExtent option for draw layers

- src/utils/legendmaker.js
> fix: no legend message

- src/controls/splash.js
> fix: make splash not assume config file

- src/controls/print/print-legend.js
> fix: only issue getlegendgraphic requests for wms layers

- src/featureinfo.js
- src/getfeatureinfo.js
Fixes #1863 
With this fix the multiselection tool will fully work and getfeatureinfo will exclude layers that are outside their zoom limits.
> fix: respect layers parameter in getFeatureInfoRequests

- src/getfeature.js
- src/layer/wfssource.js
Fixes #1848 by moving the wfs part of getFeture() to WfsSource class as it already urlecodes arguments correctly.
Also fixes #1523 when strategy = 'all' as that wasn't fixed in #1579
Probably also solves at least part of #1534, but on the other hand, it makes #1535 and #1536 almost impossible to merge.
As a bonus some redundant code from getFeature is removed and hopefully it will be easier to implement filters for QGIS and other servers and support for different WFS versions etc by keeping all code in one place. 
I have tried to make it as backwards compatible as possible, but there is a small risk that if someone utilized or tried to compensate for the weaknesses (e.g. no coordinate transform) in a plugin or external code that may break. To my knowledge getFeature is used in search …
> fix: allow percent sign in getFeature filter

- scss/_infowindow.scss
- src/infowindow.js
- Added scrollable container for layers listed in selection.
- Added max-height for infowindow to avoid window expanding out of screen when in default position
Fixes #1866
> fix: Infowindow -headers scroll & window max-height

- src/controls/editor/copyTool.js
- src/controls/editor/drawtools.js
- src/controls/editor/edithandler.js
- src/controls/editor/shapes.js
Fixes #1872.
It is now possible to configure drawtools on _MultiLine, MultiPolygon and MultiPoint_ both on editor level and on layer level.
No actual new configuration needed, but it is possible to use the aforementioned geometry types in configuration. Note that layers with geometry typ _MultiLineString_ is configured as _MultiLine_ as _LineString_ already was configured as _Line_.
Also note that there are no draw tools available for any kind of points and lines, but that's outside the scope of this PR. If there ever emerges any tools for these geometry types it will be possible to configure them.
Documentation will be updated accordingly.
> Fix:support for MultiLine, MultiPolygon and MultiPoint in drawtools

- scss/externs/_awesomplete.base.scss
- scss/externs/_awesomplete.theme.scss
- src/controls/legend.js
- src/controls/search.js
Fixes #1827 
Set max height element containing search result so it won't overflow the legend container and make it scrollable. Also set the width to match the legend.
> fix: set maxheight for layer search

- origo.js
Fixes #667.
Quick and dirty. Doesn't work with iframe embedded maps, though.
> fix: enable keyboard navigation on load

- src/featureinfo.js
- src/layer/agsfeature.js
- src/layer/geojson.js
- src/maputils.js
- src/viewer.js
Fixes #1900
Moved the rendering of the popup to the _featuresloadend_ event of the source as the layer event _postrender_ seems to be fired before features have been fetched from the source. Or possibly fired several times where the first is in a useless extent that does not load any features. This is probably due to a change in open layers.
As a bonus it fixes a bug in fetureInfo.showFeatureInfo that threw an exception when only one feature was sent. Previous implementation of sharemap did not suffer from this as the _postrender_ event caller swallowed the exception and the functionality that was cut short due to the exception was zooming to the feature, which no one was missing as sharemap always includes center and zoom in the links so the map was already panned to the desired extent. …
> fix: sharemap popup not displayed

- scss/_print.scss
- src/controls/print/print-component.js
Suggestion for an indicator in addition to tiles appearing at the edges of the print map and the two print buttons being greyed out that the print map is loading. Aims to fix #1871 
It looks like the larger "global" print spinner that shows when printing -> png and shows in the middle of the print map preview, more directly tied to the map not being finished that way I thought.
Draft pr less because I think it needs anything else and more because it may need to be something different. There are various ways of implementing a spinner or progress bar. As for the resident options in Origo, the "global" spinner is in a different place in the DOM (for a reason I guess) and has logic for that purpose (well looks rather). The "progress" control doesn't take configuration presently and is …
> feature: spinner for print map loading indicator

- src/controls/legend/group.js
Fix for issue with long group names pushes buttons aside after #1896
> fix: long group names

- src/controls/print/print-resize.js
- src/extensions.js
- src/extensions/olms.js
- src/style.js
The olms extension now rescales mapbox vector tiles when changing the dpi of a print.
The extension creates one style for each configured print resolution, which is then applied when said print resolution is chosen.
Fix for [#1801](https://github.com/origo-map/origo/issues/1801)
> Fix: Rescale vector tiles depending on dpi in print

- src/style/drawstyles.js
- src/style/styletemplate.js
- src/style/stylewindow.js
Closes #1941 
Enables rotation for text and point in draw control.
> feature: rotate text and point in draw control

- src/controls/print/print-component.js
- src/controls/print/print-resize.js
Correct print scales are now retained even when the ConstrainResolution option is true.
ConstrainResolution gets temporarily set to false when using the print component and is restored once the print component is closed.
Fixes #1934 in regard to ConstrainResolution. The scales are however still constrained by the max and min resolutions of the map, regardless of if ConstrainResolution is true or false.
> Fix: Correct print scales even when constrainResolution is true

- .eslintrc.json
Aims to fix #1956 
(The lint workflow runs the "lint" script which uses eslint so it should receive the same update)
> fix: update linter ecmascript version and keep up to date

- .github/workflows/lint.yml
Aims to fix #1958 
I've checked https://github.com/actions/setup-node which indicates the major versions of Node are supported (and 20 is the current lts, well together with 18).  ( Bard says with confidence that the provided yml changes are appropriate. ) 
Here goes
> fix: update lint workflow

- src/controls/search.js
Fixes #1228
Use infowindow for search result if set
> feature: infowindow for search

- src/controls/search.js
- src/featureinfo.js
> fix: maxZoomLevel for searchlist

- src/controls/search.js
> feature: new search params

- src/popup.js
This is my attempt to add a minimize button to popup (fix for https://github.com/origo-map/origo/issues/1945). It works, but I would appreciate if someone with more experience could make the code less ugly.
> Added minimize button to popup

- origo.js
Fixes #1972 by adding the following properties to the global Origo object:
- Origo.Loader.show
- Origo.Loader.hide
- Origo.Loader.withLoading
- Origo.Loader.getInlineSpinner
> feature: expose loader and spinner

- src/controls/legend.js
Makes the background layer buttons wrap. https://github.com/origo-map/origo/issues/1981
> Make it possible to have more backgroud layers

- src/layer/wfssource.js
Fixes #1997.
Corrects a mistake that caused typenames to not be prepended when fetching features from a QGIS Server source using IDs.
> Fix missing typenames for QGIS Server sources

- scss/_logger.scss
- scss/origo.scss
- src/components/logger.js
- src/ui/modal.js
- src/viewer.js
Fixes #1982 
I think it's not complete but useful as it is and something to build upon, eg a console window would be nice. 
As of now, this component makes it possible to render short messages for the user, either as a toast or modal with some input parameters.
Input parameters:
title
message
status (some bootstrap classes and colors; success, info, warning, danger, light(default))
duration (miliseconds, modal defaults to 0 and toast to 5000)
icon (only for toast)
`origo.api().getLogger().createToast({status: 'warning', duration:2000, icon: '#ic_home_24px', title: 'Rubrik på meddelandet', message:'Innehållet måste vara intressant, annars är det onödigt. <br> HTML funkar'})`
Toast
`origo.api().getLogger().createModal({status: 'success', duration:10000, title: 'Rubrik på meddelandet', …
> feature: logger component

- src/getfeatureinfo.js
Seeks to fix #2001  , in the alternative fashion.
Yes, I made `getFeatureInfoUrl` less robust in a recent pr and I could still remedy that function. The only place it is being used though is in the function I am proposing to change, from `Promise.all` to `Promise.allSettled`. So if `getFeatureInfoUrl` trips for any reason, like assuming everything is json when something isn't, that featureInfo call is discarded rather than allowed to render all concurrent featureInfo calls useless.
(The function in the PR is also somewhat rewritten for readability. I did not find it an easy read before)
> fix: make getfeatureinfo requests not fail together

- src/layer/wfssource.js
Fixes #1932
Makes it possible to set a query parameters as a source option or with the api like: 
`source.getOptions().queryParams={viewParams: 'scenario1'};`
Useful for instance when [[Parameterizing SQL Views](https://docs.geoserver.org/2.23.x/en/user/data/database/sqlview.html#parameterizing-sql-views)]
Yeah the url concatenation ain't beautiful but will do until someone wants to give it some tlc.
> feature: queryParams for wfssource

- src/featureinfo.js
- src/getattributes.js
- src/getfeatureinfo.js
- src/models/SelectedItem.js
- src/utils/attachmentclient.js
Fixes #1975 by adding the _async createContentAsync()_ method on _SelecedItem_ class. While doing that all code that creates the async content has been moved from _featureinfo.js_ to _getfeatureinfo.js_ while keeping the functionality intact.
For "standard" use of Origo, this PR will not change anything. The main benefit is that is is now possible to create SelectedItems containing async content and display them in InfoWindow from api or plugins, as the _SelectedItem_ class is exposed in the global Origo object.
> Moved attachments and related tables from featureinfo to SelectedItem

- scss/_tooltip.scss
- src/controls/editor/editortemplate.js
- src/controls/editor/relatedtablesform.js
Fixes #1989
- Fixes for tooltips lagging and getting stuck if the pointer happens to hover over the tooltip. (see issue for details)
- Fix for tooltips appearing behind other elements. (see issue for details)
- Addition of tooltips for editor tools.
- Fix for tooltip appearance in related tables form.
New tooltips
Related tables changes
> Tooltips, fixes and addition

- src/controls/draw/drawtools.js
- src/controls/draw/shapes.js
- src/style/drawstyles.js
- src/style/stylewindow.js
Fixes #2012 
Configure the draw control like this to be able to draw squares and circles:
```
{
"name": "draw",
"options": {
"buttonText": "Rita",
"drawTools": {
"Polygon": ["freehand", "box", "square", "circle"],
"LineString": ["freehand"]
}
}
}
```
> feature: circle and square as polygon draw shapes

- src/controls/position.js
Fixes #2022. Now the `noPositionText` works as in documentation again:
- If empty string: last know coordinate is displayed
- If missing: no text is shown (actually a non-breaking space)
- If non-empty string: the configured text is displayed
> fix: last known coordinate in position control

- src/permalink/permalinkstore.js
> Fix map name parsing in permalink store getState() function

- src/controls/measure.js
- src/style/drawstyles.js
Seeks to fix #2023 
It introduces a highlight to the measure line in order to increase its visibility on various backgrounds, by default a light blue highlight (it was an idea pitched in a meeting some time ago and it is a shorter route than adapting measure to employ the stylewindow that draw uses)
Configurable via a new prop for the measure control:
```json
{
"name": "measure",
"options": {
"hideWhenEmbedded": true,
"showSegmentLengths": true,
"highlightColor": "rgba(230, 126, 34, 0.7)"
}
},
```
> feature: add configurable highlight to measure line for visibility

- package-lock.json
- package.json
Fixes #2049 and upgrades some other dependencies
> deps: OL v10.2.0 and some other deps

- src/controls/print/print-legend.js
> fix: make print legend layer order match legend layer order

- origo.js
Found out that this will work with plugins that has a layer type which is missing in Origo and want to add it.
The key is that the layer type should be added before starting Origo.
Closes #2031
> fix: expose layertype

- src/selectionmanager.js
Fixes #2026 by making SelectionManager to display the selection in InfoWindow even if the "infoWindow"-setting is `overlay` or `sidebar`.
This will result in api-calls to SelectionManager always showing the result in infoWindow while featureInfo will obey the infoWindow-setting. It may seem a bit confusing but the old behavior was to only display the selection in the map and not show any infoWindow at all during the same circumstances.
This will only affect calls directly to SelectionManager using the api, e.g. from the MultiSelect-plugin.
> Always show infowindow

- scss/_infowindow.scss
- src/infowindow.js
I created a minimize button for the infowindow (like I've previously did for the popup https://github.com/origo-map/origo/pull/1949).
I'm not sure if or how the tabindex should be changed though.
> Add minimize button to infowindow

- src/controls/position.js
> fix: Make position control work without additional projection codes

- src/getCapabilities.js
- src/viewer.js
Fixes #1588
When capabilitiesURL for a source is set, the getCap doc will be saved unless opted out ( `"saveCapabilitiesDoc": false` ). 
Configured like:
```
"source": {
"local": {
"url": "http://localhost:8080/geoserver/ows",
"capabilitiesURL": "http://localhost:8080/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities",
"saveCapabilitiesDoc": false
}
},
```
and accessible with `origo.api().getMapSource()['local'].capabilitiesDoc`
> feature: Store getCapabilites document for source

- src/controls/editor/edithandler.js
Fixes #2072
Adds possibility to trace other features when drawing new features. As a bonus the snap tolerance can configured.
Tracing starts by snapping to a feature and clicking, thus setting a vertex. All possible paths that are traceable are lit up and the mouse can only be moved along the highlighted paths until clicked, which sets another vertex and leaves tracing but the draw interaction is still active so it is possible to jump to another features or just draw wherever.
Snapping must be active for this functionality to be meaningful as it is almost impossible to hit a line exactly. All snap layers are used for tracing.
Disclaimer: most of the cool stuff are implemented by OL, and as such there are some limitations in how much the user experience can be changed.
This PR only …
> feature: add trace to draw interaction

- src/viewer.js
Fixes #2094 
viewer.removeGroup() also removes subgroups
> fix: viewer.removeGroup() also removes subgroups

- src/getfeatureinfo.js
Fixes #2108 Try different infoFormats if getFeatureInfo request fails with the configured infoFormat (application/geojson or application/geo+json)
> fix: Test other infoFormat when getFeatureInfo fails

- src/controls/legend/group.js
Fixes #2113 
Subgroups in a group with `draggable: true` can be moved just like other layers.
> Feature: Make subgroups draggable

- src/controls/about.js
- src/controls/geoposition.js
- src/controls/home.js
- src/controls/zoom.js
- src/loc/en_US.json
- src/loc/sv_SE.json
> feature: localize of zoom, geoposition, about and home control

- src/controls/editor.js
- src/controls/editor/edithandler.js
- src/controls/editor/editortemplate.js
- src/controls/editor/editortoolbar.js
- src/utils/topology.js
Fixes #2073
Adds a new button to the editor toolbar with modify tools that is activated when the correct geometry for that tool is selected. Currently the only available tool is split-line-by-point, which does just that: select a line feature, select the split tool and click where on the selected line it should be split. It cuts the original feature and creates a new with the rest of the line. The copy gets all attributes from the original feature (except id).
To activate the modify tools menu the editor control must be configured with:
`"modifyTools": true`
The configuration is only on editor level for now. In the future one could imaging having it on layer level as well or specify which tools are available.
As a bonus Edithandler and EditToolbar are rewritten as Components so they can …
> Edit split line tool

- src/controls/legend.js
- src/controls/legend/overlays.js
- src/controls/legend/visibleOverlays.js
Fixes #2095 
Replaces #2097 
The issue was related to visibleLayersControl
> fix: Adding layers to map without overlays

- src/controls/print/print-legend.js
Fixes #2092 by generating valid legend graphics for Geoserver _Layer Groups._
Should generate all rules for all layers in a _Layer Group_ in print legend.
There are some limitations:
1. If a style has several rules, the rules must be named (same as with ordinary WMS layers)
2. A Group Layer must use the default style for each contained layer, i.e. not define another style when used inside the Group Layer, otherwise the map legend and print legend will display different symbols.
3. A top level (without workspace) Group Layer can only contain layers with unique names through all workspaces.
These limitations are all a result of missing information in the response from the  getLegendGraphic as JSON request. To overcome that a bunch of Geoserver api request would have to be performed, but …
> Fix print composite layer legend

- scss/_infowindow.scss
Aims to fix #2148  (22.5px seems to be the element's height when text is supplied (incl when the option isn't supplied)
> fix: give the iw title area a minimum height

- src/controls/editor/edithandler.js
Fixes #2152 by assigning trace layer to group 'none', making legend not displaying it.
No new configuration.
No new documentation.
> Removed tracelayer from legend

- src/controls/legend/moreinfobutton.js
Aims to fix #2127 and preserve current behavior (minus the crash).
> fix: make layer removal happen after setting popupmenu visibility

- src/utils/legendmaker.js
- src/utils/legendrender.js
Fixes #2160.
A tricky one this one... Old implementation used `Circle()` to render a legend icon for symbols of type `Line` and `Polygon`. #2120 redefined some defaults for Circle() to match the defaults for OpenLayers' defaults for the regular shape circle in the map. But when called to generate an icon for a polygon or line symbol there shouldn't be any default fill.
I solved it by separating Polygon and Line icon functions from Circle. The diff may look a bit strange but there was already a function called Polygon and one called Line. They were never called, but had to exist as legendmaker checked for their existance against the _styleType_. I copied the old implementation of `Circle()` to `Polygon()` and had `Line()` call `Polygon()` to restore the behavior for lines and polygons …
> fix: default fill in legend symbol

- src/controls/scalepicker.js
- src/utils/numberformatter.js
This proposed change reverts some of the localization from the scalepicker control and makes the numberformatter not attempt to localize the number it produces if no localization object accompanies the invocation.
The target is to make print's and the scalepicker's scale selectors work again (regardless of the currently chosen language) and as such fix #2192 
(To localize the scale selector numbers I believe #2193 needs to be remedied first)
> fix: make scale selectors work again

- src/featureinfo.js
- src/getattributes.js
- src/getfeatureinfo.js
- src/models/SelectedItem.js
- src/viewer.js
Seeks to fix #2164 .
Random thoughts:
- localizing units of measurement as @MattiasSp mentioned today would include number conversion and unit appending and it would go outside of the scope of intl.NumberFormat afaIct It could be a nice improvement down the line, especially if users in London are accustomed to seeing miles and feet when employing the ruler tool in their local web map.
- I don't pretend to understand why getAttributes and getAttributesAsync are both used when infoclicking a vector layer :)
> feature: localize area, length functions when used for layer attributes
