editor.json
src/viewer.js

Added matrixid options for wmts source

---

css/style.css
src/mapmenu.js

Added scrollbar to mapmenu

---

src/getfeature.js

Getfeature

---

css/style.css
src/featureinfo.js
src/featurelayer.js
src/permalink/permalink.js
src/permalink/permalinkparser.js
src/permalink/permalinkstore.js
src/sharemap.js
src/style/pin.js
src/style/styletypes.js
src/utils/geturl.js
src/utils/isurl.js
src/utils/urlparser.js
src/viewer.js

Added permalink

---

editor.html
index.html
mapquest.html
package.json

This PR is first step to solve #1

Renamed bundle to origo

---

origo.js
src/controlinitialiser.js
src/maploader.js
src/viewer.js

Can we merge this? The build file for embedded maps will be a separate PR. First step to solve #83

Moved away control initialising from viewer

---

src/transactionhandler.js

Added isActive check in transactionhandler

---

package.json

Upgraded to jQuery 2.2.4

---

css/style.css
src/editor.js
src/editortoolbar.js
src/featureinfo.js
src/geoposition.js
src/getattributes.js
src/home.js
src/legend.js
src/mapmenu.js
src/mapwindow.js
src/modal.js
src/popup.js
src/print.js
src/search.js
src/sharemap.js
src/sidebar.js
src/templates/editortoolbar.template.handlebars
src/templates/viewer.handlebars
src/transactionhandler.js
src/utils.js
src/viewer.js

Added o-prefix to origo classes and id

---

src/featureinfo.js
src/popup.js
src/search.js
src/viewer.js

This fixes #91 and makes Popup work better with overlays.

Remove overlays

---

src/viewer.js

Removed getEditLayer

---

src/editortoolbar.js
src/geoposition.js
src/legend.js
src/mapmenu.js
src/popup.js
src/print.js
src/search.js
src/sharemap.js
src/sidebar.js
src/transactionhandler.js

This PR solves #80 and #81 . Can we merge this?

Removed touchend

---

css/style.css
package.json

Added svg events fix for Edge

---

src/legend.js

Replaced for loop with forEach

---

src/utils.js

Fixes #99 . To make it work I also fixed a problem with the createElement method. Can we merge this @jokd @markus659 ?

Added method to create svg

---

css/style.css
index.json
origo.js
src/about.js

Added control to show general information about the map. Solves #160.

Added about control

---

src/viewer.js
tasks/build-ol-full.json
tasks/build-ol-standard.json

Added topojson support

---

src/geoposition.js

This PR fixes #141 . Also made some code improvements according our style guide.

Removed wrong this

---

src/layer/wfs.js
src/layer/wms.js
src/layer/wmts.js
src/layer/xyz.js
src/layercreator.js

Ows regression

---

css/style.css
index.json
scss/_button.scss
scss/_container.scss
scss/_geolocation.scss
scss/_home.scss
scss/_mapmenu.scss
scss/_measure.scss
scss/_toolbar.scss
scss/_viewer.scss
scss/externs/_ol.scss
scss/origo.scss
src/geoposition.js
src/home.js
src/mapmenu.js
src/measure.js
src/rotate.js
src/scaleline.js
src/templates/viewer.handlebars
src/zoom.js

Added toolbars for control target

---

conf/origoConfig.js
css/style.css
scss/_legend.scss
scss/_mapmenu.scss
scss/_modal.scss
scss/_popup.scss
scss/_search.scss
scss/_variables.scss
scss/_viewer.scss
scss/externs/_ol.scss
scss/externs/_twitter-typeahead.scss
scss/origo.scss
src/attribution.js
src/utils/elquery.js
src/viewer.js

Replaced media query with el query

---

css/style.css
origo.js
scss/_no-map.scss
scss/origo.scss
src/maploader.js
src/templates/viewer.handlebars
src/utils/rendererror.js
src/utils/supports.js

Adds error message for implementation of #212

Added error handling for browser support

---

package.json
src/home.js
src/maputils.js
src/viewer.js
tasks/build-ol-embed.json
tasks/build-ol-standard.json

Removed deprecated methods. Solves #116. Required for solving other issues.

Upgrade to OL 4.1.0

---

src/layer/wmts.js

Added missing wmts source options

---

src/editor/edithandler.js
src/modal.js

Added static as modal option

---

package.json

Fixes #254 , This is a quite small patch for ol and there seems to be no problem to upgrade.

Updated to ol 4.1.1

---

src/editor/edithandler.js
tasks/build-ol-standard.json

Added default-value

---

src/geoposition.js

This one-liner fixes #231. Not too much to it really, but I would appreciate an extra look at it just in case as I'm not completely sure what the issue is referring to.

Replaced setview and setzoom in geoposition

---

index.json
src/geoposition.js

Fixed animation issue in geoposition

---

src/editor.js

Added editable as an layer configuration

---

src/style.js

Made style fixes

---

src/legend.js

Fixes #278 Simply prepend instead of append when building the legend.

Fixed the reversed legend bug

---

.gitignore
package.json
tasks/build-ol-embed.json
tasks/build-ol-standard.json

This PR is an ol upgrade tol 4.3.4 and solves #313 . There is a problem with custom builds in this version of ol which is solved and will be included in the next release of ol. Meanwhile see https://github.com/openlayers/openlayers/pull/7229 how to fix.

Upgraded to ol 4.3.4

---

src/layer/wms.js
src/maputils.js
src/viewer.js

Fixes #319 
This PR gives the possibility to set the format on either layer or source level for WMS requests. It also gives more options when creating a tilegrid.

wms format and tilegrid options

---

src/measure.js
tasks/build-ol-standard.json

Fixes #307 Simplified the measure-control by switching to the new ol.Sphere.getArea / ol.Sphere.getLength methods.

Simplified measurefunction

---

src/layer/vector.js

Added cluster support for geojson and topojson

---

src/legend.js

Tooltip for background maps in legend

---

index.json
src/templates/viewer.handlebars
src/viewer.js

This would fix #354. It also fixes #355.

Added pageSettings

---

package.json

Updated uglify-js to 3.2.0

---

scss/_viewer.scss
src/fullscreen.js
src/maploader.js

Fixes #366 . It would be great if we can merge this before the first release, since this is a quite important thing to function properly,

Fixed full screen problems

---

scss/_search.scss
src/search.js

Fixed search input on android

---

src/scale.js

Fixed scale change event handling

---

README.md
package.json

Upgraded to node-sass 4.7.2

---

package.json

Upgraded to jquery 3.3.1

---

src/search.js

Fixed max limit issue in search

---

src/maputils.js
src/style.js

Fixed center point for style

---

src/featureinfo.js

Added featureinfo clickevent option

---

src/editor/editform.js

Added datetype to editform

---

src/layer/wfs.js

Fixed wfs encoding problem

---

scss/_popup.scss
src/popup.js

Fix for popup.js

---

src/viewer.js

Fix for mapmenu.js

---

scss/_sidebar.scss

z-index of sidebar

---

src/getfeatureinfo.js
src/maputils.js

Fixed multi-feature info click error

---

scss/_featureinfo.scss
scss/origo.scss
src/getattributes.js

Fixes #485
Added fixed width div

Fix for popup bug

---

src/layer/vector.js

Removed deprecated ol.source.ImageVector

---

src/controls/measure.js

Fix for measure control with custom projections

---

src/featureinfo.js

Fix for featureinfoTitle

---

src/featureinfo.js

Check if layer variable is defined in featureinfo

---

src/controls/editor/editform.js

No more unwanted spaces.

---

src/featureinfo.js

Added check for layer object in featureinfo

---

src/featureinfo.js
src/geometry/getcenter.js
src/getattributes.js
src/getfeatureinfo.js
src/utils/replacer.js

Fix for infoclick on ags and wms

---

scss/origo.scss
src/featureinfo.js
src/sidebar.js

Fix for sidebar

---

src/controls/splash.js

Splash fix

---

src/controls/legend/overlay.js
src/controls/legend/overlays.js
src/layer.js

This fixes #569 and also fixes #570.

Add removable option for layers

---

src/layer/vector.js
src/style.js

Fixed cluster size indicator

---

src/controls/editor/edithandler.js

Updates edithandler.js

---

scss/_search.scss

Fixed search on android

---

src/featureinfo.js
src/featurelayer.js

Fixes #566
Share map with search results from visible layer

Alternative to #578

---

package.json
tasks/webpack.dev.js

Updated webpack-dev-server version

---

src/style.js

Falls back on default style instead of throwing error

---

package.json

Fixes Install error for node-versions > 9

---

src/utils/round.js

Fixes #443 
Instead of adding round2 this method updates the existing round. 
Simple test: 
https://es6console.com/jmhf4lkb/

Updates round

---

package.json

updates jquery

---

conf/origoControls.js
scss/_progressbar.scss
scss/origo.scss
src/controls.js
src/controls/progressbar.js

Adds Progressbar

---

src/controls/editor/agstransaction.js

updates agsTransaction

---

scss/ui/_flex.scss
src/components/main.js

lefthandtools-marginfix, Fix for issue #587

---

src/style/stylefunctions/default.js

Fixed default style for points

---

src/layer/wfs.js

removes jquery from wfs fixes issue #650

---

src/layer/geojson.js

Tested with. 
add this [geojson](https://www.malardalskartan.se/origo/v2.0.1/data/origo/ledig_naringsmark.geojson) to your local data/origo.

remove jquery from geojson Issue #636

---

src/layer/osm.js

index.json as config will suffice.

removes jquery from osm fixes issue #644

---

src/layer/wms.js

removes jquery from wms fixes issue #652

---

src/layer/topojson.js

[./data/origo/](https://www.malardalskartan.se/origo/v2.0.1/data/origo/socken.json)

removes jquery from topojson fixes issue #646

---

src/layer/wmts.js

This config is for testing basemaps using the WMTS layer type, discard unrelated controls, groups, sources and styles in the config. 
```{
"controls": [{
"name": "home"
},
{
"name": "geoposition"
},
{
"name": "mapmenu"
},
{
"name": "sharemap"
},
{
"name": "print"
},
{
"name": "legend"
},
{
"name": "search",
"options": {
"url": "https://www.malardalskartan.se/origoserver/singlesearch",
"layerNameAttribute": "TYPE",
"idAttribute": "GID",
"searchAttribute": "NAMN",
"geometryAttribute": "GEOM",
"hintText": "Sök adress...",
"hint": false
}
}
],
"projectionCode": "EPSG:3010",
"projectionExtent": [
-1678505.1838360203,
4665380,
2431912.7361639794,
8775797.92
],
"proj4Defs": [{
"code": "EPSG:3010",
"alias": "urn:ogc:def:crs:EPSG::3010",
"projection": "+proj=tmerc +lat_0=0 +lon_0=16.5 +k=1 …
```

remove jquery from wmts layer type and fixes issue #654

---

src/layer/agstile.js

removes jquery from agstile, issue #634

---

src/layer/vectortile.js

If someone has a VectorTile config that is open to anyone feel free to share it.

removes jquery from vectortile fixes issue #648

---

src/layer/xyz.js

If someone has a config that is public for test, please supply.

removes jquery from xyz fixes issue #656

---

src/layer/agsfeature.js

Fixes Issue #623
Tested with: 
Add these images to img/png under root for testing.
[Forskoleverksamhet](https://www.malardalskartan.se/origo/v2.0.1/img/png/Forskoleverksamhet_skugga.png)
[Svar_14](https://www.malardalskartan.se/origo/v2.0.1/img/png/Svart_14.png)

Removes jQuery from agsFeature, fixes issue #623

---

src/controls/editor/editform.js

similar config as date and:
"type": "time"

added time as input type

---

src/utils/imageresizer.js

Fixes issue with rotation and formats other than jpeg.

imageresizer, Fixes issue #628

---

origo.js

Exposed ol/interaction

---

src/featureinfo.js
src/featurelayer.js

Fix for cluster and share map issue

---

src/controls/editor.js

Fixes #681 , a bug where infoclick and editor were both active.

Fixes bug for infoclick and editor

---

src/featureinfo.js

Update featureinfo.js
Similar fix has been done earlier and then undone, so I dont know if this would work or cause a problem I cant find?
Fixes #688

Sidebar-fix

---

.gitignore

Fixes #617
Added plugins folder to ignore.

Added plugins folder to ignore.

---

index.html

Added a link to shortcut icon for Origo exemple

---

src/controls/draganddrop.js
src/controls/legend/overlays.js

Solves issue where drag-and-dropped layers always turned up in the root of the legend

Fixes #693

---

src/getattributes.js

Updates getattributes.js

---

css/svg/material-icons.svg
scss/ui/_icon.scss
scss/ui/_variables.scss
scss/ui/helpers/_padding.scss
scss/ui/helpers/_sizes.scss
scss/ui/helpers/_text.scss
src/components/footer.js
src/controls/position.js
src/ui.js
src/ui/button.js
src/ui/collapse.js
src/ui/dom/createelement.js
src/ui/dropdown.js

Fixes #701 
_Please note that this component may require some additional development for smoother implementation in different contexts._
The dropdown component options:
**direction**: 'up' or 'down', sets in which direction the dropdown curtain opens (default is 'down'),
**cls**: dropdown component wrapper class,
**containerCls**: dropdown curtain container class,
**buttonContainerCls**: dropdown button container class,
**buttonCls**: dropdown button class,
**buttonIconCls**: dropdown button arrow icon class,
**style**: style parameters
The example in the gif below is initiated like this: 
```
const dropdown = Dropdown({
direction: 'up',
cls: 'o-dropdowntest text-white text-smallest flex',
containerCls: 'bg-grey-darker',
buttonContainerCls: 'height-125',
buttonCls: 'rounded bg-black …
```

Added UI dropdown component

---

src/controls/editor/editform.js
src/getattributes.js

This PR is another way to solve #552 and introduces the number and hidden input types for the editor form. 
Along the hidden type it would be nice to introduce some default values/functions to populate the field. Eg todays date.

Added number and hidden as input types

---

scss/ui/_input.scss
src/controls/legend/overlayproperties.js

Idea for solving #127, adds a slider in the layer tab. No configuration at this moment so it is shown for every layer.

Fixes #127, layer transparency

---

scss/ui/_button.scss
src/controls/externalurl/externalurlSeveralButtons.js
src/controls/externalurl/externalurlSingleButton.js
src/controls/fullscreen.js
src/controls/geoposition.js
src/controls/home.js
src/controls/mapmenu.js
src/controls/measure.js
src/controls/zoom.js

Round icons

---

src/controls/editor/edithandler.js
src/getattributes.js

Fixes #678 
Now (img: {attributename}) will work the same way as (type:image, name:{attributename}) to work in form as well as popup.

Image as attribute

---

src/controls/legend/overlayproperties.js

Origo ol6 transparency

---

scss/_popup.scss
src/featureinfo.js

Fixes #723 
Fix for click-through svgs and rolls back to previous carousel look

Fix for popup issue

---

src/controls/editor/edithandler.js

Enterkey returns false

---

src/controls/legend.js
src/controls/mapmenu.js

Added class

---

scss/_tooltip.scss
scss/origo.scss
src/controls/externalurl/externalurlSeveralButtons.js
src/controls/externalurl/externalurlSingleButton.js
src/controls/measure.js
src/ui/button.js

Fixes #583 
Used by externalurl, measure and map menu at the moment.

Added tooltips to buttons

---

scss/_ol.scss

Overrides ol css

---

src/controls/geoposition.js

Fixes #747 
```
{
"name": "geoposition", 
"options": {
"active": true,
"zoomLevel": 14
}
}
```

Added active option

---

src/viewer.js

Adds startExtent option

---

scss/ui/_input.scss

Blocks horizontal resize textbox

---

src/controls/editor/editform.js
src/controls/editor/edithandler.js
src/utils/validate.js

Adds validation to all relevant types

---

src/map.js

#765 We could turn keyboard off until map tab-index is solved #667

No keyboard 

---

scss/ui/_input.scss

Repairs input button style

---

src/controls/editor.js

Round up edit button

---

scss/ui/_input.scss

Searchwindow style 

---

src/layer/xyz.js

Fixes #778 
To config xyz layers according to documentation.

Syntax for source

---

src/viewer.js

Fixes bugs in the zoom to feature function

---

src/controls/editor/drawtools.js
src/controls/editor/editorlayers.js
src/dropdown.js

Fixes #801.
Can be tested with the editor by switching layers and draw tools (if available).

Replaced Jquery in src/dropdown.js

---

src/controls/legend/overlays.js

Fixes #772
Removed the button and collapse function from the header since we now have a close button.

Removed collapse button

---

package.json
scss/_ol.scss

Bump OL to 6.2.0

---

PLUGINS.md
README.md

Fixes #815. More detailed information can be added later.

Added PLUGINS.md

---

README.md

Issue #754 
Removes the text "support of old browsers" in the README

Removes support text

---

src/controls/print/print-component.js

Fixes #784
Further improvement would be to remove the portrait/landscape orientation buttons when setting custom sizes since they are confusing.

Fixes print bug when height>width

---

DEVELOPING.md

Remove IE 10 support text

---

src/style/measure.js

Allow overflow on area measure labels

---

src/viewer.js

Expose methods in viewer for lmsearch-plugin

---

scss/_search.scss
scss/ui/_variables.scss
scss/ui/helpers/_helpers.scss
src/controls/search.js

Rounded search bar

---

src/featureinfo.js
src/popup.js
src/sidebar.js

Clear features when closing popup

---

src/controls/editor.js
src/controls/fullscreen.js
src/controls/geoposition.js
src/controls/home.js
src/controls/legend.js
src/controls/zoom.js

Fixes #767.
If anything is wrong or missing, please feel free to change it.
Sorry for making many commits in this pr, I know there should only be one with all changes in it. I apologize for my poor knowledge of git.

Adds tooltip text

---

scss/origo.scss

Fixes bug when panning in Chrome

---

src/controls/legend.js
src/ui/button.js
src/ui/icon.js

Background maps tooltip

---

.travis.yml
README.md

This PR would resolve issue 640.

Adds CI config for Travis CI

---

package-lock.json
package.json

updates packages

---

src/controls/print/logo.js
src/controls/print/print-component.js
src/controls/print/print-map.js
src/controls/print/print-settings.js

Addresses issue #879 
Test config:
`    {
"name": "print",
"options": {
"logo": {
"cls": "padding-bottom-small",
"src": "css/png/logo_print.png",
"style": {
"height": "3rem"
}
}
}
},
`

Enable config of logo in print control.

---

origo.js

Expose Openlayers format through Origo for the draw-plugin.

---

index.json
scss/ui/helpers/_text.scss
src/controls/legend.js
src/controls/legend/overlayproperties.js
src/controls/legend/overlays.js

Added the possiblity to add label for transparency slider on layers in legend control.
Closes #898

Label for transparency slider on layers in legend control

---

scss/ui/_validate.scss
src/controls/editor/editform.js
src/controls/editor/edithandler.js
src/utils/validate.js

Adds required to form validation

---

src/controls/editor/edithandler.js

Fix for #908

---

index.json

Overlay as default infowindow

---

src/getattributes.js
src/utils/replacer.js

fixes #547 
Example of 0 value in attribute:
Example of 0 value in attribute for popup:

Value zero attribute fix

---

src/infowindow.js
src/models/SelectedItem.js

Fixing one little thing that was missing in PR for Infowindow. Plus fixing Linter problem in a nother file related to that PR.
Fixes issue #890

Error message read from config

---

origo.js

Added collection, legendmaker exports

---

scss/_print.scss
src/controls/print/created-control.js
src/controls/print/index.js
src/controls/print/page.template.js
src/controls/print/print-component.js
src/controls/print/print-settings.js
src/controls/print/print-settings.template.js

Closes #916 
There is a fault I'm having trouble finding the cause for. First open the print control and deselect the "Använd marginaler". Then close the print control and open it again. The result is a white border at the bottom that shouldn't be there, see image.

Adds created datetime label for print control

---

scss/ui/helpers/_margin.scss
src/popup.js
src/sidebar.js
src/ui/modal.js

Close button align

---

src/controls/sharemap.js
src/featureinfo.js
src/featurelayer.js
src/viewer.js

Share map with clustered features

---

scss/_infowindow.scss

Another try!
Fixes issue #930 .

Z-index for "infowindow"

---

src/getattributes.js

@center transformation fix

---

src/permalink/permalinkstore.js
src/viewer.js

Only vector features can be shared in permalink

---

src/infowindow.js

Made it possible to have multiple exports for a layer with different file extensions.
Fixes issue #941 .
Also made some changes for error message, filename and button text.

Moved exportFileName and some small fixes

---

src/controls/legend/overlays.js

Fixes #936 
Only tested in IE11 but if it works there it must be solid.

Added fix for IE in overlay.js

---

src/viewer.js

Fixes #946 
Can be tested with test config and the wfs layer

Fit to feature in share map

---

origo.js
src/controls/search.js

This fixes the issue #939 but there are still errors. This doesnt add too much code and awaits no Origo support for IE

IE not like includes

---

index.json

Updates footer config

---

scss/_o-scale.scss
scss/_position.scss
scss/_viewer.scss
scss/origo.scss
scss/ui/_input.scss
scss/ui/_variables.scss
src/controls/legend.js
src/controls/legend/overlayproperties.js
src/controls/legend/overlays.js
src/controls/position.js
src/controls/scale.js

Fixes #955
Fixes #956
Fixes #914

Fixed position on coordinates

---

scss/_viewer.scss

Minimizes middle content

---

src/controls/legend.js
src/ui/slidenav.js

Added slidenav transition state check

---

src/controls/print/print-component.js
src/controls/print/print-settings.js
src/controls/print/print-settings.template.js
src/controls/print/rotation-control.js
src/ui/input-range.js

Ability to change rotation of map in the print control

---

src/utils/replacer.js

Avoid returning empty object

---

src/controls/legend.js
src/controls/mapmenu.js
src/controls/print/print-settings.js
src/popup.js
src/sidebar.js
src/ui/button.js
src/ui/modal.js

Fixes #1006 
Added ariaLabel option for buttons

ariaLabel option

---

src/controls/legend/group.js
src/controls/legend/grouplist.js

Adds abstract for groups

---

scss/_popup.scss
scss/_sidebar.scss
scss/externs/_core.scss

css fix for #1000

---

scss/_position.scss
src/controls/measure.js
src/controls/position.js

Enhanced measure control on touch devices

---

scss/_searchList.scss
scss/origo.scss
src/controls/editor/addons/searchList/searchList.js
src/controls/editor/addons/searchList/utils/attachBtnEvent.js
src/controls/editor/addons/searchList/utils/attachInputEvent.js
src/controls/editor/addons/searchList/utils/awesomeImage.js
src/controls/editor/addons/searchList/utils/awesomeParser.js
src/controls/editor/addons/searchList/utils/fetchImg.js
src/controls/editor/addons/searchList/utils/makeEmptyList.js
src/controls/editor/addons/searchList/utils/moveBtn.js
src/controls/editor/editform.js
src/controls/editor/edithandler.js
src/utils/validate.js

This is an updated PR of PR #604 
Fixes #463

adds searchList

---

scss/ui/helpers/_sizes.scss
src/controls/print/description-control.js
src/controls/print/index.js
src/controls/print/print-component.js
src/controls/print/print-settings.js
src/controls/print/print-settings.template.js
src/controls/print/title-control.js

Fixes #1033 
Makes it possible to change alignment and size of the title for the printed map.

Formatting of the title

---

jsconfig.json

adds jsconfig

---

package-lock.json
package.json
tasks/webpack.common.js

Add source-map loader

---

src/controls/print/logo.js
src/controls/print/north-arrow.js
src/controls/print/print-component.js

Print IE and Edge fix

---

src/maputils.js

Method that takes a GeoJSON and returns a WKT string

---

scss/ui/_collapse.scss
src/controls/print/print-settings.js
src/ui/collapse.js

Print settings have separate collapse container class

---

package-lock.json
package.json
tasks/webpack.prod.js

No updates for Webpack and webpack-cli, current latest versioners are tested but are not stable to upgrade to. Fixes #1054

Package updates

---

origo.js
package-lock.json

replaces polyfill with core-js and regenerator-runtime

Updates babel/polyfill use 

---

src/controls/measure.js
src/permalink/permalinkstore.js

Adds clear button

---

.vscode/launch.json
tasks/webpack.lint.dev.js

fixes issue #1069 
Visual Studio Code (vscode)
- Debbuger for Chrome
- Debbuger for Firefox
- Debugger for Edge
`npm install`

adds debugger config

---

scss/_modal.scss

Suggestion for #1085.  Looks good on the mobile unit mentioned in issue but no other mobile models is tested.

Max height adjustment

---

src/controls/editor/addons/searchList/searchList.js

removes jq in searchList

---

scss/ui/_collapse.scss

Fixed arrow in legend

---

package.json
src/controls/search.js

Last stuff to drop jQuery

---

scss/_popup.scss

Fix to center arrows in carousel.

---

scss/_popup.scss
src/featureinfo.js

Autopan and search

---

src/controls/measure.js

Fixes ghost labels

---

scss/ui/helpers/_helpers.scss
src/controls/legend/overlay.js

Fixes #499 
Fades the row in the legend if outside min/max scale

Solution to indicate if layer is outside min/max

---

scss/_measure.scss
src/controls/measure.js

Less disturbing labels on the sections of the measuring tool.
Doesn't solve #1035 but makes it less annoying

Smaller labels .measure

---

src/controls/measure.js

Clear tooltip on deactivate

---

src/controls/measure.js

Fix for when other tool is activated

---

src/controls/measure.js

Fixes #1144 
Removes requirement for the position control

Removes requirement for the position control

---

src/controls/editor/edithandler.js

Fixed editor image upload bug

---

tasks/webpack.lint.dev.js

port update

---

scss/ui/_validate.scss
src/controls/editor/editform.js

Validate style override no more and error message class fix

---

src/oglide.js

Bullets lag

---

src/controls/print/print-settings.js
src/controls/print/print-settings.template.js

Fixes #1168
Hides the rotation slider when enableRotation: false in config (An Openlayers setting)

Fix when rotation is disabled

---

src/controls/editor/editform.js

Fixed typo in editform.js

---

src/controls/measure.js

Fixed toggleFeatureInfo event bug when measure is inactive

---

src/utils/download.js

Fix for iPhone

---

src/getattributes.js

Does this fixes #1187 and not causing a bug in other cases? @jokd
The bug was caused by me by creating a function for 2 almost identical pieces of code snippets and missing the subtle difference.

Bug fix for when name is also url

---

src/utils/templatehelpers.js

Fixes #1103 
Checks if value is null or empty before adding it.

Fix for null values for geopackage source

---

scss/_print.scss
src/controls/print/print-interaction-toggle.js
src/controls/print/print-settings.js
src/controls/print/print-settings.template.js

Round buttons in print control

---

src/utils/download.js

Fixes print image export

---

src/controls/editor/drawtools.js
src/controls/editor/editdispatcher.js
src/controls/editor/edithandler.js

Fixed drawtool not showing up after jqeyry dependencies was removed.
Also fixed rectangle tool events working.

#1210 Fix for drawtools in edit toolbar

---

src/viewer.js

Expose map config

---

src/featureinfo.js

featureinfoTitle bugfix

---

src/getattributes.js

Changes target for links

---

src/controls/draganddrop.js
src/style.js

Be able to put a style on Draganddrop control

---

src/utils/replacer.js

Fix that handles multiple nested attributes in a html attribute string

---

scss/_icon.scss
scss/_variables.scss
scss/glide/_custom.scss

Redesigned image carousel UI

---

src/controls/print/print-component.js
src/controls/print/print-interaction-toggle.js
src/map.js
src/mapinteractions.js

Fixes bug introduced in #1254 where the map crashes unless pageSettings is set in the config.

Fix when pagesettings is not set

---

scss/origo.scss

Overscroll behavior on body

---

src/featureinfo.js

Fixes #1279 - Rearranges stuff for the carousel

Fix for map not autopanning vertically

---

src/components/footer.js
src/controls/about.js
src/controls/legend.js
src/controls/legend/overlay.js
src/controls/mapmenu.js
src/controls/position.js
src/controls/scalepicker.js
src/ui/dropdown.js
src/utils/legendrender.js

Closes #1297
Introdueses new setting in footer for pageSettings:
```
"pageSettings": {
"footer": {
"img": "/img/png/logo.png",
"alt": "logo",
```

Accessability fixes with button labels and icon alt

---

origo.js
package-lock.json
package.json

added elm-pep dependency

---

src/utils.js

Expose slugify util method

---

package-lock.json
package.json
src/controls/position.js

Upped ol to 6.6.1

---

index.html

Adds a Content-Security-Policy

---

src/controls/legend/overlays.js

Fixed missing group bug, added warning

---

index.html

Update to PR #1335 since the CSP created a problem with event handling.

Changed to 'unsafe-inline' keyword

---

package-lock.json
package.json
tasks/webpack.analyze.js
tasks/webpack.copy-dev.js
tasks/webpack.copy.js
tasks/webpack.dev.js
tasks/webpack.lint.dev.js
tasks/webpack.lint.prod.js
tasks/webpack.prod.js

Fixes #1337
Some changes had to be done in the webpack files

Openlayers 6.7.0

---

src/controls/fullscreen.js

Changed class

---

origo.js

Adds featureinfoOptions to default config

---

package-lock.json
package.json

dom-to-image version

---

index.html

Update CSP to allow data for image etc

---

src/controls/legend.js
src/ui/collapse.js
src/ui/slidenav.js

Exlude tab order when legend minimized

---

scss/externs/_awesomplete.base.scss
scss/externs/_awesomplete.theme.scss
src/controls/legend.js

Closes #1330 
Introduces 3 new configurations options:
```
{
"name": "legend",
"options": {
"searchLayersControl": true,
"searchLayersMinLength": 2,
"searchLayersLimit": 10
}
}
```

Search function for legend control

---

scss/_bookmark.scss
scss/origo.scss
src/controls/bookmarks.js

Show focus for bookmark control

---

package-lock.json
package.json

Solves #1108
Tested with default config as well as @johnnyblasta 400 toppar and seems to work well.

Update Glide js

---

src/controls/measure.js

Fixes lingering segment label button

---

src/getfeatureinfo.js

Proposes to fix #1384. Thanks for suggestion toward solution @tonnyandersson , I've tested AGS_TILE featureinfoLayer: wms layer and vice versa, both seem to work.

fix: make featureinfoLayer layer property function

---

src/selectionmanager.js

Expands group when more than one item is added

---

src/selectionmanager.js

Fixes #1444.
Thanks for the `selectionGroup` tip, @jokd.

Account for layer in alreadyExists

---

src/viewer.js

Avoids map crashing when layer is not present in the map

---

src/featureinfo.js
src/permalink/permalinkstore.js
src/selectionmanager.js
src/viewer.js

Adds share map functionality when using infowindow

---

src/controls/legend/overlays.js
src/ui/input-range.js

Closes #1452 and fixes partly or completely #1402

Fixes tab and focus on layer properties

---

src/controls/draganddrop.js

Fixes #1458 
Ensure unique names are used for drag and drop-layers

Ensure that layername is unique

---

src/controls/draganddrop.js
src/controls/print/print-component.js

Readds the drag and drop control after print

---

scss/ui/_validate.scss
src/controls/editor/editform.js
src/controls/editor/edithandler.js
src/controls/editor/wfstransaction.js
src/utils/validate.js

Fixes #1143 and some other bugs in editor

Editform overhaul

---

scss/ui/_button.scss

A different background color for not icon class buttons when focus

---

src/controls/editor/editform.js

Swaps back default date

---

src/controls/print/description-control.js
src/controls/print/orientation-control.js
src/controls/print/print-component.js
src/controls/print/resolution-control.js
src/controls/print/size-control.js
src/controls/print/title-control.js

Adds a aria-label to close button.

---

src/controls/legend.js

Make legend search placeholder text configurable

---

src/viewer.js

Add permalink methods to viewer

---

DEVELOPING.md

Removed IE11

---

src/controls/print/print-resize.js
src/style.js

Fixes #1546 in a quick and dirty way

Labels in print bug fix

---

src/controls/print/print-legend.js

Fetches information from ArcGIS MapServer for the legend, similarly to how to is done for WMS legends support JSON legends.
Also detects WMS layers that are actually MapServer layers and uses the same code for those, since MapServer does not provide JSON data for WMS legends.
Closes: #1525

Create a print legend for AGS_* layers

---

src/layer/wmts.js

WMTS print fix

---

package-lock.json
package.json

ol-v6.15.1

---

scss/externs/_ol.scss

fix: Scalebar styling

---

PLUGINS.md

docs: add swiper and oidc to plugins.md

---

scss/externs/_awesomplete.theme.scss

fix: Legend search on mobile

---

src/controls/print/print-resize.js

fix: print with overlays from LMSearch plugin

---

PLUGINS.md

Proposed elaboration on plugins-documentation in plugins.md. 
Additional improvements are more than welcome. 
Fixes: #1636

docs: Plugins doc

---

package-lock.json
package.json

dep: node-sass v7.0.3

---

package-lock.json
package.json
src/controls/print/print-component.js

Fixes #1647 
New version of OpenLayers and removed monkey patch in print component since OL now have native support for transform: scale

dep: OL v7.2.2

---

src/controls/editor/addons/searchList/searchList.js
src/controls/editor/addons/searchList/utils/awesomeParser.js
src/controls/editor/edithandler.js

Closes #1608  
SearchList now offers a value-label dropdown similar to HTML select.
To access this new feature a label is added to each value in the list object like this:
```json
"list": [
{
"label": "Sel",
"value": "1"
},
{
"label": "Stan",
"value": "2"
},
{
"label": "Obygden",
"value": "3"
}
],
```
And in the _config_ property a `"useBackingValue": true,` setting must be added. Configuration is fully backwards compatible. This setting implies `allowOnlyfromList`, so it does not have to be set implicitly.
What happens is that the searchList displays and searches on _label_ but _value_ is stored in database. When opening the searchList, a reverse lookup is performed. When using a dynamic remote source, a new server endpoint must be implemented in order for the reverse lookup to work. The …

feature: support for value and label in searchList

---

src/featureinfo.js
src/getfeatureinfo.js

Fixes #1618 
Also somewhat rewrites code added in #1652 since it didn't fully handle maps where grouplayers were both visible and hidden.

fix: getfeatureinfo on grouplayers

---

.github/workflows/lint.yml
package.json
src/viewer.js

Note that the lint issues found are fixed by #1552.

Fix lint issues and add linting to CI

---

src/controls/bookmarks.js
src/controls/editor.js
src/controls/externalurl/externalurlSeveralButtons.js
src/controls/externalurl/externalurlSingleButton.js
src/controls/fullscreen.js
src/controls/geoposition.js
src/controls/home.js
src/controls/legend.js
src/controls/mapmenu.js
src/controls/measure.js
src/controls/position.js
src/controls/print/print-resize.js
src/controls/scale.js
src/controls/scalepicker.js
src/controls/search.js
src/infowindow_expandableList.js
src/viewer.js

fix: lint issues

---

scss/externs/_awesomplete.base.scss
src/controls/legend.js

Fixes #1641 
Had to set a fixed width to input and result list to not have it runaway outside page. Perhaps some css guru has a fix for this?

fix: search result not hidden in legend search

---

src/controls/editor/shapes.js

fix: drawtool other than default

---

src/components/centermarker.js
src/controls/externalurl/externalurlSeveralButtons.js
src/viewer.js

Fixes #1672
Adds a centerMarker component to the viewer, easy to use with show/hide methods. Future improvements are to use this along with eg the position control, but they somehow has to respect each other.

feature: center marker for externalurl

---

CONTRIBUTING.md

docs: updating guidelines for PR subject

---

src/controls/print/print-legend.js
src/utils/legendmaker.js

Fixes #1693
Print legend will behave the same as the map legend for hidden styles

fix: hidden styles in print legend

---

package-lock.json
package.json

Fixes #1702 
Updated to OpenLayers v7.3.0 and ol-mapbox-style v10.1.0 in package.json

dep: OpenLayers v7.3.0

---

src/getattributes.js

feature: support timestamp when formatDatetime

---

src/getfeatureinfo.js

fix: fix invalid backslash in json

---

src/layer/wms.js

fix: avoid redundant scale param for WMS getlegendgraphic

---

src/viewer.js

feature: defaultLayerParams in config

---

package-lock.json
scss/_infowindow.scss
src/geom.js
src/geometry/getarea.js
src/geometry/getlength.js
src/infowindow.js
src/infowindow_expandableList.js
src/selectionmanager.js
src/utils/formatareastring.js
src/utils/formatlengthstring.js

Fixes #1662.
This PR consists of two parts. The first is adding a length HTML attribute helper function. It works like the undocumented `area` helper function. this is __not__ needed in order to aggregate length or area, it is just to display length and area for individual features. See below for how to configure:
```
{
"name": "fritext"
},
{
"html": "Areal: {{@area(3)}}"
}
],
{
"name": "fritext"
},
{
"html": "Length: {{@length(3)}}"
}
],
```
The second part is the actual aggregation of attributes. It only works when using _SelectionManager (InfoWindow, InfoWindow list view, MultiSelelect plugin)_.  Any (numeric) attribute can be aggregated in addition to area and length.
Aggregation of the configured attributes are displayed at the bottom of the InfoWindow …

feature: Add group aggregations and length attribute helper.

---

src/layer/wms.js

Example add on layer in config `"filter": "owner = 'me'"`
Closes: #1726

feature: filter on wms layer

---

package-lock.json
src/featureinfotemplates.js
src/getattributes.js

Fixes #1718 by passing the layer along with the feature attributes

feature: layer param in featureinfo templates

---

src/getattributes.js

fix: ignore attribut type hidden for featureinfo

---

src/viewer.js

fix: use mapstate-sharemap with draw control

---

src/style/drawstyles.js
src/style/styletemplate.js

feature: map marker

---

src/maputils.js
src/viewer.js

feature: make markers queryable and removeable

---

README.md

docs: change README.md discussion invite link to discord

---

package-lock.json
package.json

dep: OL v7.4.0

---

src/utils/legendmaker.js

fix: check for preferred icon on compounded style

---

src/controls/legend/overlay.js
src/controls/legend/overlayproperties.js
src/layer/wms.js
src/style.js
src/ui/dom/createelement.js
src/utils/legendmaker.js

Fixes #1629
"thematicStyling": true as a layer option will enable this feature. Works hopefully with both vector and wms services. However, using stylePicker will override this setting for now.

feature: thematic styling

---

src/controls/draw/drawhandler.js

fix: drawHandler event bug

---

src/utils/legendmaker.js

fix: check for filter before adding as thematic style

---

package-lock.json
package.json

dep: OL v7.5.1

---

src/controls/print/print-interaction-toggle.js

fix: print: change inital state for button when "mapInteractionsActive": true

---

src/controls/search.js

fix: remove suggestions when clearing search field

---

css/svg/material-icons.svg
src/featureinfo.js
src/viewer.js

Fixes #1832 and #1829
Adds an icon and makes a couple of minor non breaking changes

fix: minor changes for the multiselection plugin

---

src/controls/print/print-legend.js

fix: bad url for icon in print legend

---

src/controls/draganddrop.js

fix: style for all types in draganddrop

---

src/controls/draw.js
src/controls/draw/drawhandler.js

fix: draw control: set layer as visible when activated

---

src/controls/legend.js

fix: hide legend button when hideWhenEmbedded is true

---

src/controls/print/print-legend.js

Fixes #1837, simply by not adding an icon if the layer styleName is "origoStylefunction".

fix: fixed broken image issue for dynamically styled layers

---

src/controls/legend/visibleOverlays.js

Adjusted css class in overlays component.
Fixes #1845

fix: scrolling in visibleLayersControl 

---

src/style/drawstyles.js
src/style/stylewindow.js

fix: styling multigeometries

---

scss/_infowindow.scss

fix: removed max-height for infowindow item

---

scss/_infowindow.scss

fix: scrollbars for infowindow

---

src/controls/print/print-resize.js

fix: missing styleName parameter in print-resize.js

---

src/controls/legend/group.js

fix: change word wrapping for subgroups

---

scss/ui/_flex.scss
src/controls/legend/group.js
src/ui/collapseheader.js

fix: group header issue

---

scss/_infowindow.scss

fix: wrap in infowindow to stopp overflow

---

src/getfeature.js
src/layer/wfssource.js

fix: allow 0 as ID

---

README.md

doc: update README.md node version

---

src/controls/print/index.js
src/controls/print/title-control.js

Change Rubrik to Titel in the Print settings. Aims to fix #2000

feat: change Rubrik to Titel

---

src/controls/measure.js

fix: check for zero value on area

---

src/featureinfo.js

Fixes #2080 
Adds itemadded event for the featureinfo component when items are added to the carousel

feature: New event for featureinfo

---

src/controls/bookmarks.js
src/loc/en_US.json
src/loc/sv_SE.json

feature: localize bookmark control

---

src/ui/dropdown.js

Fixes #2110
Adds getItems, setItems and toggle methods to the component as well as the possibility to set items on initialization by adding a items array in the options param.

feature: New methods for dropdown ui component

---

src/style.js
src/utils/legendmaker.js
src/utils/legendrender.js

Closes #2088 
Styling example:
```
"statusrubrik_filter_arrende": [
[
{
"triangle": {
"radius": 7,
"stroke": {
"color": "rgba(0,0,0,1)",
"width": 1
},
"fill": {
"color": "rgba(0,255,0,1)"
}
},
"filter": "[VernacularName] == 'jättebalsamin'",
"label": "jättebalsamin"
}
],
[
{
"star": {
"radius": 7,
"stroke": {
"color": "rgba(0,0,0,1)",
"width": 1
},
"fill": {
"color": "rgba(0,255,0,1)"
}
},
"filter": "[VernacularName] == 'kanadagås'",
"label": "kanadagås"
}
],
[
{
"square": {
"radius": 7,
"stroke": {
"color": "rgba(0,0,0,1)",
"width": 1
},
"fill": {
"color": "rgba(255,255,0,1)"
}
},
"filter": "[VernacularName] == 'vresros'",
"label": "vresros"
}
],
[
{
"cross": {
"radius": 7,
"stroke": {
"color": "rgba(255,255,0,1)",
"width": 2
}
},
"filter": "[VernacularName] == 'blomsterlupin'",
"label": …
```

feature: more styling options with RegularShape

---

src/controls/position.js
src/loc/en_US.json
src/loc/sv_SE.json

feature: localize position control

---

.github/workflows/codeql-analysis.yml

fix: update workflow file to codeql v3

---

src/controls/scalepicker.js
src/loc/en_US.json
src/loc/sv_SE.json
src/maputils.js
src/utils/numberformatter.js

feature: localize scalepicker

---

README.md

fix: remove outdated Hallstakartan link

---

src/style/stylewindow.js

fix: backgroundfill for text in draw

---

src/selectionmanager.js

fix: localize infowindow area and length sum functions

---

src/controls/splash.js
src/loc/en_US.json
src/loc/sv_SE.json

feature: localize splash control
